using Microsoft.Extensions.DependencyInjection;

namespace Hot.SMPP.Installers;

public static class InetLabSMPPInstaller
{
    public static void AddInetLabLicense(this IServiceCollection _)
    {
        string licenseContent = @"-----BEGIN INETLAB LICENSE------
O6RZPXESHTVNSCAMMIFRC43IMFZGK2LU
FUZTAMBXGMYTOOBRBIGES3TFORWGCYRO
KNGVAUACBFBW63LNEBJWQ33QAMHWE4TZ
MFXEA2DPOQXGG3ZOPJ3QIELTNBQXEZLJ
OQWTONZUGU2TGOJUGMCQAAF4ZDGOTWII
AYAMBASBTYENWCEAAESKQSSVLLNSFDOE
QZ2L5QZLQ63MHM362PBEP47YAMKE4UQE
UY7CIRS7PFTGH7GSFOCSBVRCS4E5TL7K
BHQOVH37EYKMGQW3OMZMFPS6QPG4RJHP
EN3HB47NE6NAKCAWZOOL4UUH2NK7X66G
Y5KT6MX4BARUISKCPFZCG4VCQ6TCZZWR
R5PT2TNB2S3OSY2EVD2FQCQGYZ4DC2I=
-----END INETLAB LICENSE--------";

        Inetlab.SMPP.LicenseManager.SetLicense(licenseContent);

    }
}
