//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using eJuice2024;
using Hot.Web.Provider.Interfaces.Services.Ecocash;
using System;
using System.Xml.Linq;
using System.Xml.Serialization;

namespace eJuice2024
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://teleceletopuptest.telecelzimbabwe.co.zw/EstelTprServices/services/EstelTpr" +
        "Services", ConfigurationName = "eJuice2024.EstelTprServicesSoapBindingImpl")]
    public interface EstelTprServicesSoapBindingImpl
    {

        // CODEGEN: Generating message contract since the wrapper namespace (http://services.estel.com) of message getTransHistoryRequest does not match the default value (http://teleceletopuptest.telecelzimbabwe.co.zw/EstelTprServices/services/EstelTprServices)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        eJuice2024.getTransHistoryResponse getTransHistory(eJuice2024.getTransHistoryRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<eJuice2024.getTransHistoryResponse> getTransHistoryAsync(eJuice2024.getTransHistoryRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://services.estel.com) of message getBalanceRequest does not match the default value (http://teleceletopuptest.telecelzimbabwe.co.zw/EstelTprServices/services/EstelTprServices)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        eJuice2024.getBalanceResponse getBalance(eJuice2024.getBalanceRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<eJuice2024.getBalanceResponse> getBalanceAsync(eJuice2024.getBalanceRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://services.estel.com) of message getTopupRequest does not match the default value (http://teleceletopuptest.telecelzimbabwe.co.zw/EstelTprServices/services/EstelTprServices)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        eJuice2024.getTopupResponse getTopup(eJuice2024.getTopupRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<eJuice2024.getTopupResponse> getTopupAsync(eJuice2024.getTopupRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://services.estel.com) of message wallettransferRequest does not match the default value (http://teleceletopuptest.telecelzimbabwe.co.zw/EstelTprServices/services/EstelTprServices)
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        eJuice2024.wallettransferResponse wallettransfer(eJuice2024.wallettransferRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<eJuice2024.wallettransferResponse> wallettransferAsync(eJuice2024.wallettransferRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://transhistory.support.services.estel.com")]
    public partial class TransHistoryRequest
    {

        private string agentcodeField;

        private string agenttransidField;

        private string countField;

        private string fromdateField;

        private string mpinField;

        private string todateField;

        private string transidField;

        private string vendortransidField;

        private string destinationField;

        private string transtypeField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agentcode
        {
            get
            {
                return this.agentcodeField;
            }
            set
            {
                this.agentcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string fromdate
        {
            get
            {
                return this.fromdateField;
            }
            set
            {
                this.fromdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string mpin
        {
            get
            {
                return this.mpinField;
            }
            set
            {
                this.mpinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string todate
        {
            get
            {
                return this.todateField;
            }
            set
            {
                this.todateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string vendortransid
        {
            get
            {
                return this.vendortransidField;
            }
            set
            {
                this.vendortransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string transtype
        {
            get
            {
                return this.transtypeField;
            }
            set
            {
                this.transtypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://wallettransfer.support.services.estel.com")]
    public partial class WalletTransferInfoResponse
    {

        private string agentCodeField;

        private double amountField;

        private string commentsField;

        private string destinationField;

        private string requestCtsField;

        private string responseCtsField;

        private string resultCodeField;

        private string resultDescriptionField;

        private string transIdField;

        private string clientTypeField;

        private string oprWalletField;

        private string prewalletBalanceField;

        private string walletBalanceField;

        private string preoprwalletField;

        private string agenttransidField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agentCode
        {
            get
            {
                return this.agentCodeField;
            }
            set
            {
                this.agentCodeField = value;
            }
        }

        /// <remarks/>
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string requestCts
        {
            get
            {
                return this.requestCtsField;
            }
            set
            {
                this.requestCtsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string responseCts
        {
            get
            {
                return this.responseCtsField;
            }
            set
            {
                this.responseCtsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string resultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string resultDescription
        {
            get
            {
                return this.resultDescriptionField;
            }
            set
            {
                this.resultDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string transId
        {
            get
            {
                return this.transIdField;
            }
            set
            {
                this.transIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string clientType
        {
            get
            {
                return this.clientTypeField;
            }
            set
            {
                this.clientTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string oprWallet
        {
            get
            {
                return this.oprWalletField;
            }
            set
            {
                this.oprWalletField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string prewalletBalance
        {
            get
            {
                return this.prewalletBalanceField;
            }
            set
            {
                this.prewalletBalanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string walletBalance
        {
            get
            {
                return this.walletBalanceField;
            }
            set
            {
                this.walletBalanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string preoprwallet
        {
            get
            {
                return this.preoprwalletField;
            }
            set
            {
                this.preoprwalletField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://wallettransfer.support.services.estel.com")]
    public partial class WalletTransferInfoRequest
    {

        private string agentCodeField;

        private double amountField;

        private string commentsField;

        private string destinationField;

        private string mpinField;

        private string agenttransidField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agentCode
        {
            get
            {
                return this.agentCodeField;
            }
            set
            {
                this.agentCodeField = value;
            }
        }

        /// <remarks/>
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string mpin
        {
            get
            {
                return this.mpinField;
            }
            set
            {
                this.mpinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://topup.support.services.estel.com")]
    public partial class TopupResponse
    {

        private string agentCodeField;

        private string sourceField;

        private string vendortransidField;

        private string vendorcodeField;

        private string productcodeField;

        private string destinationField;

        private string typeField;

        private string agenttransidField;

        private string amountField;

        private string pramtField;

        private string poamtField;

        private string transidField;

        private string walletBalanceField;

        private string preWalletBalanceField;

        private string feeField;

        private string processingfeeField;

        private string rangeField;

        private string servicetaxField;

        private string ecessField;

        private string hcessField;

        private string entaxField;

        private string vatField;

        private string taxField;

        private string clienttypeField;

        private string resultcodeField;

        private string resultdescriptionField;

        private string requestctsField;

        private string responsectsField;

        private string responseValueField;

        private string commentsField;

        private string smsvalField;

        private string oprwalletField;

        private string preoprwalletField;

        private string customerIdField;

        private string customerAccountIdField;

        private string refillIdField;

        private string pgAuthIdField;

        private string pgtransnameField;

        private string servicenameField;

        private string posCodeField;

        private string servicetypeField;

        private string pgtransIdField;

        private string channelIdField;

        private string validityField;

        private string pre_balanceField;

        private string post_balanceField;

        private string circleidField;

        private string stateField;

        private string distributeridField;

        private string authIdField;

        private string userIdField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agentCode
        {
            get
            {
                return this.agentCodeField;
            }
            set
            {
                this.agentCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string vendortransid
        {
            get
            {
                return this.vendortransidField;
            }
            set
            {
                this.vendortransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string vendorcode
        {
            get
            {
                return this.vendorcodeField;
            }
            set
            {
                this.vendorcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string productcode
        {
            get
            {
                return this.productcodeField;
            }
            set
            {
                this.productcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string pramt
        {
            get
            {
                return this.pramtField;
            }
            set
            {
                this.pramtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string poamt
        {
            get
            {
                return this.poamtField;
            }
            set
            {
                this.poamtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string walletBalance
        {
            get
            {
                return this.walletBalanceField;
            }
            set
            {
                this.walletBalanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string preWalletBalance
        {
            get
            {
                return this.preWalletBalanceField;
            }
            set
            {
                this.preWalletBalanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string fee
        {
            get
            {
                return this.feeField;
            }
            set
            {
                this.feeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string processingfee
        {
            get
            {
                return this.processingfeeField;
            }
            set
            {
                this.processingfeeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string range
        {
            get
            {
                return this.rangeField;
            }
            set
            {
                this.rangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string servicetax
        {
            get
            {
                return this.servicetaxField;
            }
            set
            {
                this.servicetaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string ecess
        {
            get
            {
                return this.ecessField;
            }
            set
            {
                this.ecessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string hcess
        {
            get
            {
                return this.hcessField;
            }
            set
            {
                this.hcessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string entax
        {
            get
            {
                return this.entaxField;
            }
            set
            {
                this.entaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string vat
        {
            get
            {
                return this.vatField;
            }
            set
            {
                this.vatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string clienttype
        {
            get
            {
                return this.clienttypeField;
            }
            set
            {
                this.clienttypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string resultcode
        {
            get
            {
                return this.resultcodeField;
            }
            set
            {
                this.resultcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string resultdescription
        {
            get
            {
                return this.resultdescriptionField;
            }
            set
            {
                this.resultdescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string requestcts
        {
            get
            {
                return this.requestctsField;
            }
            set
            {
                this.requestctsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string responsects
        {
            get
            {
                return this.responsectsField;
            }
            set
            {
                this.responsectsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string responseValue
        {
            get
            {
                return this.responseValueField;
            }
            set
            {
                this.responseValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string smsval
        {
            get
            {
                return this.smsvalField;
            }
            set
            {
                this.smsvalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string oprwallet
        {
            get
            {
                return this.oprwalletField;
            }
            set
            {
                this.oprwalletField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string preoprwallet
        {
            get
            {
                return this.preoprwalletField;
            }
            set
            {
                this.preoprwalletField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string customerAccountId
        {
            get
            {
                return this.customerAccountIdField;
            }
            set
            {
                this.customerAccountIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string refillId
        {
            get
            {
                return this.refillIdField;
            }
            set
            {
                this.refillIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string pgAuthId
        {
            get
            {
                return this.pgAuthIdField;
            }
            set
            {
                this.pgAuthIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string pgtransname
        {
            get
            {
                return this.pgtransnameField;
            }
            set
            {
                this.pgtransnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string servicename
        {
            get
            {
                return this.servicenameField;
            }
            set
            {
                this.servicenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string posCode
        {
            get
            {
                return this.posCodeField;
            }
            set
            {
                this.posCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string servicetype
        {
            get
            {
                return this.servicetypeField;
            }
            set
            {
                this.servicetypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string pgtransId
        {
            get
            {
                return this.pgtransIdField;
            }
            set
            {
                this.pgtransIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string channelId
        {
            get
            {
                return this.channelIdField;
            }
            set
            {
                this.channelIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string pre_balance
        {
            get
            {
                return this.pre_balanceField;
            }
            set
            {
                this.pre_balanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string post_balance
        {
            get
            {
                return this.post_balanceField;
            }
            set
            {
                this.post_balanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string circleid
        {
            get
            {
                return this.circleidField;
            }
            set
            {
                this.circleidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string distributerid
        {
            get
            {
                return this.distributeridField;
            }
            set
            {
                this.distributeridField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string authId
        {
            get
            {
                return this.authIdField;
            }
            set
            {
                this.authIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://topup.support.services.estel.com")]
    public partial class TopupRequest
    {

        private string agentCodeField;

        private string mpinField;

        private string destinationField;

        private string amountField;

        private string productCodeField;

        private string commentsField;

        private string agenttransidField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agentCode
        {
            get
            {
                return this.agentCodeField;
            }
            set
            {
                this.agentCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string mpin
        {
            get
            {
                return this.mpinField;
            }
            set
            {
                this.mpinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string productCode
        {
            get
            {
                return this.productCodeField;
            }
            set
            {
                this.productCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://balance.support.services.estel.com")]
    public partial class BalanceResponse
    {

        private string agentcodeField;

        private string agentnameField;

        private string sourceField;

        private string destinationField;

        private string agenttransidField;

        private string vendorcodeField;

        private string amountField;

        private string transidField;

        private string resultcodeField;

        private string resultdescriptionField;

        private string requestctsField;

        private string responsectsField;

        private string clienttypeField;

        private string responsevalueField;

        private string commentsField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agentcode
        {
            get
            {
                return this.agentcodeField;
            }
            set
            {
                this.agentcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agentname
        {
            get
            {
                return this.agentnameField;
            }
            set
            {
                this.agentnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string vendorcode
        {
            get
            {
                return this.vendorcodeField;
            }
            set
            {
                this.vendorcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string resultcode
        {
            get
            {
                return this.resultcodeField;
            }
            set
            {
                this.resultcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string resultdescription
        {
            get
            {
                return this.resultdescriptionField;
            }
            set
            {
                this.resultdescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string requestcts
        {
            get
            {
                return this.requestctsField;
            }
            set
            {
                this.requestctsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string responsects
        {
            get
            {
                return this.responsectsField;
            }
            set
            {
                this.responsectsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string clienttype
        {
            get
            {
                return this.clienttypeField;
            }
            set
            {
                this.clienttypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string responsevalue
        {
            get
            {
                return this.responsevalueField;
            }
            set
            {
                this.responsevalueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://balance.support.services.estel.com")]
    public partial class BalanceRequest
    {

        private string agentCodeField;

        private string mpinField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agentCode
        {
            get
            {
                return this.agentCodeField;
            }
            set
            {
                this.agentCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string mpin
        {
            get
            {
                return this.mpinField;
            }
            set
            {
                this.mpinField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://transhistory.support.services.estel.com")]
    public partial class TransHistoryRecordDetail
    {

        private string agenttransidField;

        private string clienttypeField;

        private string resultcodeField;

        private string resultdescriptionField;

        private string transidField;

        private string vendorcodeField;

        private string vendortransidField;

        private string amountField;

        private string responseCTSField;

        private string transtypeField;

        private string cntField;

        private string destinationField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string clienttype
        {
            get
            {
                return this.clienttypeField;
            }
            set
            {
                this.clienttypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string resultcode
        {
            get
            {
                return this.resultcodeField;
            }
            set
            {
                this.resultcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string resultdescription
        {
            get
            {
                return this.resultdescriptionField;
            }
            set
            {
                this.resultdescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string vendorcode
        {
            get
            {
                return this.vendorcodeField;
            }
            set
            {
                this.vendorcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string vendortransid
        {
            get
            {
                return this.vendortransidField;
            }
            set
            {
                this.vendortransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string responseCTS
        {
            get
            {
                return this.responseCTSField;
            }
            set
            {
                this.responseCTSField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string transtype
        {
            get
            {
                return this.transtypeField;
            }
            set
            {
                this.transtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string cnt
        {
            get
            {
                return this.cntField;
            }
            set
            {
                this.cntField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://transhistory.support.services.estel.com")]
    public partial class TransHistoryResponse
    {

        private string agentcodeField;

        private string agenttransidField;

        private string clienttypeField;

        private string commentsField;

        private string recordCountField;

        private string recordsField;

        private string requestctsField;

        private string responsectsField;

        private string resultcodeField;

        private string resultdescriptionField;

        private TransHistoryRecordDetail transHisDetailArrayField;

        private string transidField;

        private string vendorcodeField;

        private string vendortransidField;

        private string destinationField;

        private string transtypeField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agentcode
        {
            get
            {
                return this.agentcodeField;
            }
            set
            {
                this.agentcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string clienttype
        {
            get
            {
                return this.clienttypeField;
            }
            set
            {
                this.clienttypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string recordCount
        {
            get
            {
                return this.recordCountField;
            }
            set
            {
                this.recordCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string records
        {
            get
            {
                return this.recordsField;
            }
            set
            {
                this.recordsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string requestcts
        {
            get
            {
                return this.requestctsField;
            }
            set
            {
                this.requestctsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string responsects
        {
            get
            {
                return this.responsectsField;
            }
            set
            {
                this.responsectsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string resultcode
        {
            get
            {
                return this.resultcodeField;
            }
            set
            {
                this.resultcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string resultdescription
        {
            get
            {
                return this.resultdescriptionField;
            }
            set
            {
                this.resultdescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public TransHistoryRecordDetail transHisDetailArray
        {
            get
            {
                return this.transHisDetailArrayField;
            }
            set
            {
                this.transHisDetailArrayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string vendorcode
        {
            get
            {
                return this.vendorcodeField;
            }
            set
            {
                this.vendorcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string vendortransid
        {
            get
            {
                return this.vendortransidField;
            }
            set
            {
                this.vendortransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable = true)]
        public string transtype
        {
            get
            {
                return this.transtypeField;
            }
            set
            {
                this.transtypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getTransHistory", WrapperNamespace = "http://services.estel.com", IsWrapped = true)]
    public partial class getTransHistoryRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public eJuice2024.TransHistoryRequest historyRequest;

        public getTransHistoryRequest()
        {
        }

        public getTransHistoryRequest(eJuice2024.TransHistoryRequest historyRequest)
        {
            this.historyRequest = historyRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getTransHistoryResponse", WrapperNamespace = "http://teleceletopuptest.telecelzimbabwe.co.zw/EstelTprServices/services/EstelTpr" +
        "Services", IsWrapped = true)]
    public partial class getTransHistoryResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public eJuice2024.TransHistoryResponse getTransHistoryReturn;

        public getTransHistoryResponse()
        {
        }

        public getTransHistoryResponse(eJuice2024.TransHistoryResponse getTransHistoryReturn)
        {
            this.getTransHistoryReturn = getTransHistoryReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getBalance", WrapperNamespace = "http://services.estel.com", IsWrapped = true)]
    public partial class getBalanceRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public eJuice2024.BalanceRequest balanceRequest;

        public getBalanceRequest()
        {
        }

        public getBalanceRequest(eJuice2024.BalanceRequest balanceRequest)
        {
            this.balanceRequest = balanceRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getBalanceResponse", WrapperNamespace = "http://teleceletopuptest.telecelzimbabwe.co.zw/EstelTprServices/services/EstelTpr" +
        "Services", IsWrapped = true)]
    public partial class getBalanceResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public eJuice2024.BalanceResponse getBalanceReturn;

        public getBalanceResponse()
        {
        }

        public getBalanceResponse(eJuice2024.BalanceResponse getBalanceReturn)
        {
            this.getBalanceReturn = getBalanceReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getTopup", WrapperNamespace = "http://services.estel.com", IsWrapped = true)]
    public partial class getTopupRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public eJuice2024.TopupRequest topupRequest;

        public getTopupRequest()
        {
        }

        public getTopupRequest(eJuice2024.TopupRequest topupRequest)
        {
            this.topupRequest = topupRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "getTopupResponse", WrapperNamespace = "http://teleceletopuptest.telecelzimbabwe.co.zw/EstelTprServices/services/EstelTpr" +
        "Services", IsWrapped = true)]
    public partial class getTopupResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public eJuice2024.TopupResponse getTopupReturn;

        public getTopupResponse()
        {
        }

        public getTopupResponse(eJuice2024.TopupResponse getTopupReturn)
        {
            this.getTopupReturn = getTopupReturn;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "wallettransfer", WrapperNamespace = "http://services.estel.com", IsWrapped = true)]
    public partial class wallettransferRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public eJuice2024.WalletTransferInfoRequest walletTransferInfoRequest;

        public wallettransferRequest()
        {
        }

        public wallettransferRequest(eJuice2024.WalletTransferInfoRequest walletTransferInfoRequest)
        {
            this.walletTransferInfoRequest = walletTransferInfoRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "wallettransferResponse", WrapperNamespace = "http://teleceletopuptest.telecelzimbabwe.co.zw/EstelTprServices/services/EstelTpr" +
        "Services", IsWrapped = true)]
    public partial class wallettransferResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public eJuice2024.WalletTransferInfoResponse wallettransferReturn;

        public wallettransferResponse()
        {
        }

        public wallettransferResponse(eJuice2024.WalletTransferInfoResponse wallettransferReturn)
        {
            this.wallettransferReturn = wallettransferReturn;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EstelTprServicesSoapBindingImplChannel : eJuice2024.EstelTprServicesSoapBindingImpl, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstelTprServicesSoapBindingImplClient : System.ServiceModel.ClientBase<eJuice2024.EstelTprServicesSoapBindingImpl>, eJuice2024.EstelTprServicesSoapBindingImpl
    {

        public EstelTprServicesSoapBindingImplClient()
        {
        }

        public EstelTprServicesSoapBindingImplClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public EstelTprServicesSoapBindingImplClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public EstelTprServicesSoapBindingImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public EstelTprServicesSoapBindingImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eJuice2024.getTransHistoryResponse eJuice2024.EstelTprServicesSoapBindingImpl.getTransHistory(eJuice2024.getTransHistoryRequest request)
        {
            return base.Channel.getTransHistory(request);
        }

        public eJuice2024.TransHistoryResponse getTransHistory(eJuice2024.TransHistoryRequest historyRequest)
        {
            eJuice2024.getTransHistoryRequest inValue = new eJuice2024.getTransHistoryRequest();
            inValue.historyRequest = historyRequest;
            eJuice2024.getTransHistoryResponse retVal = ((eJuice2024.EstelTprServicesSoapBindingImpl)(this)).getTransHistory(inValue);
            return retVal.getTransHistoryReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eJuice2024.getTransHistoryResponse> eJuice2024.EstelTprServicesSoapBindingImpl.getTransHistoryAsync(eJuice2024.getTransHistoryRequest request)
        {
            return base.Channel.getTransHistoryAsync(request);
        }

        public System.Threading.Tasks.Task<eJuice2024.getTransHistoryResponse> getTransHistoryAsync(eJuice2024.TransHistoryRequest historyRequest)
        {
            eJuice2024.getTransHistoryRequest inValue = new eJuice2024.getTransHistoryRequest();
            inValue.historyRequest = historyRequest;
            return ((eJuice2024.EstelTprServicesSoapBindingImpl)(this)).getTransHistoryAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eJuice2024.getBalanceResponse eJuice2024.EstelTprServicesSoapBindingImpl.getBalance(eJuice2024.getBalanceRequest request)
        {
            return base.Channel.getBalance(request);
        }

        public eJuice2024.BalanceResponse getBalance(eJuice2024.BalanceRequest balanceRequest)
        {
            eJuice2024.getBalanceRequest inValue = new eJuice2024.getBalanceRequest();
            inValue.balanceRequest = balanceRequest;
            eJuice2024.getBalanceResponse retVal = ((eJuice2024.EstelTprServicesSoapBindingImpl)(this)).getBalance(inValue);
            return retVal.getBalanceReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eJuice2024.getBalanceResponse> eJuice2024.EstelTprServicesSoapBindingImpl.getBalanceAsync(eJuice2024.getBalanceRequest request)
        {
            return base.Channel.getBalanceAsync(request);
        }

        public System.Threading.Tasks.Task<eJuice2024.getBalanceResponse> getBalanceAsync(eJuice2024.BalanceRequest balanceRequest)
        {
            eJuice2024.getBalanceRequest inValue = new eJuice2024.getBalanceRequest();
            inValue.balanceRequest = balanceRequest;
            return ((eJuice2024.EstelTprServicesSoapBindingImpl)(this)).getBalanceAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eJuice2024.getTopupResponse eJuice2024.EstelTprServicesSoapBindingImpl.getTopup(eJuice2024.getTopupRequest request)
        {
            return base.Channel.getTopup(request);
        }

        public eJuice2024.TopupResponse getTopup(eJuice2024.TopupRequest topupRequest)
        {
            eJuice2024.getTopupRequest inValue = new eJuice2024.getTopupRequest();
            inValue.topupRequest = topupRequest;
            eJuice2024.getTopupResponse retVal = ((eJuice2024.EstelTprServicesSoapBindingImpl)(this)).getTopup(inValue);
            return retVal.getTopupReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eJuice2024.getTopupResponse> eJuice2024.EstelTprServicesSoapBindingImpl.getTopupAsync(eJuice2024.getTopupRequest request)
        {
            return base.Channel.getTopupAsync(request);
        }

        public System.Threading.Tasks.Task<eJuice2024.getTopupResponse> getTopupAsync(eJuice2024.TopupRequest topupRequest)
        {
            eJuice2024.getTopupRequest inValue = new eJuice2024.getTopupRequest();
            inValue.topupRequest = topupRequest;
            return ((eJuice2024.EstelTprServicesSoapBindingImpl)(this)).getTopupAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eJuice2024.wallettransferResponse eJuice2024.EstelTprServicesSoapBindingImpl.wallettransfer(eJuice2024.wallettransferRequest request)
        {
            return base.Channel.wallettransfer(request);
        }

        public eJuice2024.WalletTransferInfoResponse wallettransfer(eJuice2024.WalletTransferInfoRequest walletTransferInfoRequest)
        {
            eJuice2024.wallettransferRequest inValue = new eJuice2024.wallettransferRequest();
            inValue.walletTransferInfoRequest = walletTransferInfoRequest;
            eJuice2024.wallettransferResponse retVal = ((eJuice2024.EstelTprServicesSoapBindingImpl)(this)).wallettransfer(inValue);
            return retVal.wallettransferReturn;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eJuice2024.wallettransferResponse> eJuice2024.EstelTprServicesSoapBindingImpl.wallettransferAsync(eJuice2024.wallettransferRequest request)
        {
            return base.Channel.wallettransferAsync(request);
        }

        public System.Threading.Tasks.Task<eJuice2024.wallettransferResponse> wallettransferAsync(eJuice2024.WalletTransferInfoRequest walletTransferInfoRequest)
        {
            eJuice2024.wallettransferRequest inValue = new eJuice2024.wallettransferRequest();
            inValue.walletTransferInfoRequest = walletTransferInfoRequest;
            return ((eJuice2024.EstelTprServicesSoapBindingImpl)(this)).wallettransferAsync(inValue);
        }
    }
}
namespace eJuice
{

    // NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
    public partial class Envelope
    {

        private EnvelopeBody bodyField;

        /// <remarks/>
        public EnvelopeBody Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
    public partial class EnvelopeBody
    {

        private getBalanceResponse getBalanceResponseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://services.estel.com")]
        public getBalanceResponse getBalanceResponse
        {
            get
            {
                return this.getBalanceResponseField;
            }
            set
            {
                this.getBalanceResponseField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://services.estel.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://services.estel.com", IsNullable = false)]
    public partial class getBalanceResponse
    {

        private getBalanceResponseGetBalanceReturn getBalanceReturnField;

        /// <remarks/>
        public getBalanceResponseGetBalanceReturn getBalanceReturn
        {
            get
            {
                return this.getBalanceReturnField;
            }
            set
            {
                this.getBalanceReturnField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://services.estel.com")]
    public partial class getBalanceResponseGetBalanceReturn
    {

        private uint agentcodeField;

        private object agentnameField;

        private object sourceField;

        private object destinationField;

        private object agenttransidField;

        private string vendorcodeField;

        private string amountField;

        private object transidField;

        private byte resultcodeField;

        private string resultdescriptionField;

        private string requestctsField;

        private string responsectsField;

        private string clienttypeField;

        private object responsevalueField;

        private object commentsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com")]
        public uint agentcode
        {
            get
            {
                return this.agentcodeField;
            }
            set
            {
                this.agentcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com", IsNullable = true)]
        public object agentname
        {
            get
            {
                return this.agentnameField;
            }
            set
            {
                this.agentnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com", IsNullable = true)]
        public object source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com", IsNullable = true)]
        public object destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com", IsNullable = true)]
        public object agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com")]
        public string vendorcode
        {
            get
            {
                return this.vendorcodeField;
            }
            set
            {
                this.vendorcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com")]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com", IsNullable = true)]
        public object transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com")]
        public byte resultcode
        {
            get
            {
                return this.resultcodeField;
            }
            set
            {
                this.resultcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com")]
        public string resultdescription
        {
            get
            {
                return this.resultdescriptionField;
            }
            set
            {
                this.resultdescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com")]
        public string requestcts
        {
            get
            {
                return this.requestctsField;
            }
            set
            {
                this.requestctsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com")]
        public string responsects
        {
            get
            {
                return this.responsectsField;
            }
            set
            {
                this.responsectsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com")]
        public string clienttype
        {
            get
            {
                return this.clienttypeField;
            }
            set
            {
                this.clienttypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com", IsNullable = true)]
        public object responsevalue
        {
            get
            {
                return this.responsevalueField;
            }
            set
            {
                this.responsevalueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://balance.support.services.estel.com", IsNullable = true)]
        public object comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }




}