'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace NyaradzoAPI
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="NyaradzoResultModel", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class NyaradzoResultModel
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private ValidResponseField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResponseDataField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorDataField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ItemField As NyaradzoAPI.AccountSummary
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultField As NyaradzoAPI.TransactionResult
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ValidResponse() As Boolean
            Get
                Return Me.ValidResponseField
            End Get
            Set
                If (Me.ValidResponseField.Equals(value) <> true) Then
                    Me.ValidResponseField = value
                    Me.RaisePropertyChanged("ValidResponse")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property ResponseData() As String
            Get
                Return Me.ResponseDataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResponseDataField, value) <> true) Then
                    Me.ResponseDataField = value
                    Me.RaisePropertyChanged("ResponseData")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property ErrorData() As String
            Get
                Return Me.ErrorDataField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorDataField, value) <> true) Then
                    Me.ErrorDataField = value
                    Me.RaisePropertyChanged("ErrorData")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Item() As NyaradzoAPI.AccountSummary
            Get
                Return Me.ItemField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemField, value) <> true) Then
                    Me.ItemField = value
                    Me.RaisePropertyChanged("Item")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Result() As NyaradzoAPI.TransactionResult
            Get
                Return Me.ResultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultField, value) <> true) Then
                    Me.ResultField = value
                    Me.RaisePropertyChanged("Result")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AccountSummary", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AccountSummary
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As String
        
        Private DateCreatedField As NyaradzoAPI.DateTimeOffset
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PolicyNumberField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceReferenceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResponseCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MonthlyPremiumField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AmountToBePaidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumberOfMonthsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResponseDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BalanceField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PolicyHolderField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BankCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TxnRefField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Id() As String
            Get
                Return Me.IdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdField, value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false, Order:=1)>  _
        Public Property DateCreated() As NyaradzoAPI.DateTimeOffset
            Get
                Return Me.DateCreatedField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DateCreatedField, value) <> true) Then
                    Me.DateCreatedField = value
                    Me.RaisePropertyChanged("DateCreated")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property PolicyNumber() As String
            Get
                Return Me.PolicyNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PolicyNumberField, value) <> true) Then
                    Me.PolicyNumberField = value
                    Me.RaisePropertyChanged("PolicyNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property SourceReference() As String
            Get
                Return Me.SourceReferenceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceReferenceField, value) <> true) Then
                    Me.SourceReferenceField = value
                    Me.RaisePropertyChanged("SourceReference")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Status() As String
            Get
                Return Me.StatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusField, value) <> true) Then
                    Me.StatusField = value
                    Me.RaisePropertyChanged("Status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property ResponseCode() As String
            Get
                Return Me.ResponseCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResponseCodeField, value) <> true) Then
                    Me.ResponseCodeField = value
                    Me.RaisePropertyChanged("ResponseCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property MonthlyPremium() As String
            Get
                Return Me.MonthlyPremiumField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MonthlyPremiumField, value) <> true) Then
                    Me.MonthlyPremiumField = value
                    Me.RaisePropertyChanged("MonthlyPremium")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property AmountToBePaid() As String
            Get
                Return Me.AmountToBePaidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AmountToBePaidField, value) <> true) Then
                    Me.AmountToBePaidField = value
                    Me.RaisePropertyChanged("AmountToBePaid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property NumberOfMonths() As String
            Get
                Return Me.NumberOfMonthsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumberOfMonthsField, value) <> true) Then
                    Me.NumberOfMonthsField = value
                    Me.RaisePropertyChanged("NumberOfMonths")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Property ResponseDescription() As String
            Get
                Return Me.ResponseDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResponseDescriptionField, value) <> true) Then
                    Me.ResponseDescriptionField = value
                    Me.RaisePropertyChanged("ResponseDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Property Balance() As String
            Get
                Return Me.BalanceField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BalanceField, value) <> true) Then
                    Me.BalanceField = value
                    Me.RaisePropertyChanged("Balance")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public Property PolicyHolder() As String
            Get
                Return Me.PolicyHolderField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PolicyHolderField, value) <> true) Then
                    Me.PolicyHolderField = value
                    Me.RaisePropertyChanged("PolicyHolder")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public Property BankCode() As String
            Get
                Return Me.BankCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BankCodeField, value) <> true) Then
                    Me.BankCodeField = value
                    Me.RaisePropertyChanged("BankCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property TxnRef() As String
            Get
                Return Me.TxnRefField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TxnRefField, value) <> true) Then
                    Me.TxnRefField = value
                    Me.RaisePropertyChanged("TxnRef")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TransactionResult", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TransactionResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DateTimeOffset", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DateTimeOffset
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="NyaradzoAPI.NyaradzoSoap")>  _
    Public Interface NyaradzoSoap
        
        'CODEGEN: Generating message contract since element name AppKey from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ProcessPayment", ReplyAction:="*")>  _
        Function ProcessPayment(ByVal request As NyaradzoAPI.ProcessPaymentRequest) As NyaradzoAPI.ProcessPaymentResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ProcessPayment", ReplyAction:="*")>  _
        Function ProcessPaymentAsync(ByVal request As NyaradzoAPI.ProcessPaymentRequest) As System.Threading.Tasks.Task(Of NyaradzoAPI.ProcessPaymentResponse)
        
        'CODEGEN: Generating message contract since element name AppKey from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Refund", ReplyAction:="*")>  _
        Function Refund(ByVal request As NyaradzoAPI.RefundRequest) As NyaradzoAPI.RefundResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Refund", ReplyAction:="*")>  _
        Function RefundAsync(ByVal request As NyaradzoAPI.RefundRequest) As System.Threading.Tasks.Task(Of NyaradzoAPI.RefundResponse)
        
        'CODEGEN: Generating message contract since element name AppKey from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AccountQuery", ReplyAction:="*")>  _
        Function AccountQuery(ByVal request As NyaradzoAPI.AccountQueryRequest) As NyaradzoAPI.AccountQueryResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AccountQuery", ReplyAction:="*")>  _
        Function AccountQueryAsync(ByVal request As NyaradzoAPI.AccountQueryRequest) As System.Threading.Tasks.Task(Of NyaradzoAPI.AccountQueryResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ProcessPaymentRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProcessPayment", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As NyaradzoAPI.ProcessPaymentRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As NyaradzoAPI.ProcessPaymentRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ProcessPaymentRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AppKey As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public PolicyNumber As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public reference As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public amount As Decimal
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AppKey As String, ByVal PolicyNumber As String, ByVal reference As String, ByVal amount As Decimal)
            MyBase.New
            Me.AppKey = AppKey
            Me.PolicyNumber = PolicyNumber
            Me.reference = reference
            Me.amount = amount
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ProcessPaymentResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProcessPaymentResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As NyaradzoAPI.ProcessPaymentResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As NyaradzoAPI.ProcessPaymentResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ProcessPaymentResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ProcessPaymentResult As NyaradzoAPI.NyaradzoResultModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ProcessPaymentResult As NyaradzoAPI.NyaradzoResultModel)
            MyBase.New
            Me.ProcessPaymentResult = ProcessPaymentResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RefundRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Refund", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As NyaradzoAPI.RefundRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As NyaradzoAPI.RefundRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RefundRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AppKey As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public reference As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AppKey As String, ByVal reference As String)
            MyBase.New
            Me.AppKey = AppKey
            Me.reference = reference
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RefundResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RefundResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As NyaradzoAPI.RefundResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As NyaradzoAPI.RefundResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class RefundResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public RefundResult As NyaradzoAPI.NyaradzoResultModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RefundResult As NyaradzoAPI.NyaradzoResultModel)
            MyBase.New
            Me.RefundResult = RefundResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AccountQueryRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AccountQuery", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As NyaradzoAPI.AccountQueryRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As NyaradzoAPI.AccountQueryRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AccountQueryRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AppKey As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public PolicyNumber As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AppKey As String, ByVal PolicyNumber As String)
            MyBase.New
            Me.AppKey = AppKey
            Me.PolicyNumber = PolicyNumber
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AccountQueryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AccountQueryResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As NyaradzoAPI.AccountQueryResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As NyaradzoAPI.AccountQueryResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AccountQueryResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AccountQueryResult As NyaradzoAPI.NyaradzoResultModel
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AccountQueryResult As NyaradzoAPI.NyaradzoResultModel)
            MyBase.New
            Me.AccountQueryResult = AccountQueryResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface NyaradzoSoapChannel
        Inherits NyaradzoAPI.NyaradzoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class NyaradzoSoapClient
        Inherits System.ServiceModel.ClientBase(Of NyaradzoAPI.NyaradzoSoap)
        Implements NyaradzoAPI.NyaradzoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NyaradzoAPI_NyaradzoSoap_ProcessPayment(ByVal request As NyaradzoAPI.ProcessPaymentRequest) As NyaradzoAPI.ProcessPaymentResponse Implements NyaradzoAPI.NyaradzoSoap.ProcessPayment
            Return MyBase.Channel.ProcessPayment(request)
        End Function
        
        Public Function ProcessPayment(ByVal AppKey As String, ByVal PolicyNumber As String, ByVal reference As String, ByVal amount As Decimal) As NyaradzoAPI.NyaradzoResultModel
            Dim inValue As NyaradzoAPI.ProcessPaymentRequest = New NyaradzoAPI.ProcessPaymentRequest()
            inValue.Body = New NyaradzoAPI.ProcessPaymentRequestBody()
            inValue.Body.AppKey = AppKey
            inValue.Body.PolicyNumber = PolicyNumber
            inValue.Body.reference = reference
            inValue.Body.amount = amount
            Dim retVal As NyaradzoAPI.ProcessPaymentResponse = CType(Me,NyaradzoAPI.NyaradzoSoap).ProcessPayment(inValue)
            Return retVal.Body.ProcessPaymentResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NyaradzoAPI_NyaradzoSoap_ProcessPaymentAsync(ByVal request As NyaradzoAPI.ProcessPaymentRequest) As System.Threading.Tasks.Task(Of NyaradzoAPI.ProcessPaymentResponse) Implements NyaradzoAPI.NyaradzoSoap.ProcessPaymentAsync
            Return MyBase.Channel.ProcessPaymentAsync(request)
        End Function
        
        Public Function ProcessPaymentAsync(ByVal AppKey As String, ByVal PolicyNumber As String, ByVal reference As String, ByVal amount As Decimal) As System.Threading.Tasks.Task(Of NyaradzoAPI.ProcessPaymentResponse)
            Dim inValue As NyaradzoAPI.ProcessPaymentRequest = New NyaradzoAPI.ProcessPaymentRequest()
            inValue.Body = New NyaradzoAPI.ProcessPaymentRequestBody()
            inValue.Body.AppKey = AppKey
            inValue.Body.PolicyNumber = PolicyNumber
            inValue.Body.reference = reference
            inValue.Body.amount = amount
            Return CType(Me,NyaradzoAPI.NyaradzoSoap).ProcessPaymentAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NyaradzoAPI_NyaradzoSoap_Refund(ByVal request As NyaradzoAPI.RefundRequest) As NyaradzoAPI.RefundResponse Implements NyaradzoAPI.NyaradzoSoap.Refund
            Return MyBase.Channel.Refund(request)
        End Function
        
        Public Function Refund(ByVal AppKey As String, ByVal reference As String) As NyaradzoAPI.NyaradzoResultModel
            Dim inValue As NyaradzoAPI.RefundRequest = New NyaradzoAPI.RefundRequest()
            inValue.Body = New NyaradzoAPI.RefundRequestBody()
            inValue.Body.AppKey = AppKey
            inValue.Body.reference = reference
            Dim retVal As NyaradzoAPI.RefundResponse = CType(Me,NyaradzoAPI.NyaradzoSoap).Refund(inValue)
            Return retVal.Body.RefundResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NyaradzoAPI_NyaradzoSoap_RefundAsync(ByVal request As NyaradzoAPI.RefundRequest) As System.Threading.Tasks.Task(Of NyaradzoAPI.RefundResponse) Implements NyaradzoAPI.NyaradzoSoap.RefundAsync
            Return MyBase.Channel.RefundAsync(request)
        End Function
        
        Public Function RefundAsync(ByVal AppKey As String, ByVal reference As String) As System.Threading.Tasks.Task(Of NyaradzoAPI.RefundResponse)
            Dim inValue As NyaradzoAPI.RefundRequest = New NyaradzoAPI.RefundRequest()
            inValue.Body = New NyaradzoAPI.RefundRequestBody()
            inValue.Body.AppKey = AppKey
            inValue.Body.reference = reference
            Return CType(Me,NyaradzoAPI.NyaradzoSoap).RefundAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NyaradzoAPI_NyaradzoSoap_AccountQuery(ByVal request As NyaradzoAPI.AccountQueryRequest) As NyaradzoAPI.AccountQueryResponse Implements NyaradzoAPI.NyaradzoSoap.AccountQuery
            Return MyBase.Channel.AccountQuery(request)
        End Function
        
        Public Function AccountQuery(ByVal AppKey As String, ByVal PolicyNumber As String) As NyaradzoAPI.NyaradzoResultModel
            Dim inValue As NyaradzoAPI.AccountQueryRequest = New NyaradzoAPI.AccountQueryRequest()
            inValue.Body = New NyaradzoAPI.AccountQueryRequestBody()
            inValue.Body.AppKey = AppKey
            inValue.Body.PolicyNumber = PolicyNumber
            Dim retVal As NyaradzoAPI.AccountQueryResponse = CType(Me,NyaradzoAPI.NyaradzoSoap).AccountQuery(inValue)
            Return retVal.Body.AccountQueryResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function NyaradzoAPI_NyaradzoSoap_AccountQueryAsync(ByVal request As NyaradzoAPI.AccountQueryRequest) As System.Threading.Tasks.Task(Of NyaradzoAPI.AccountQueryResponse) Implements NyaradzoAPI.NyaradzoSoap.AccountQueryAsync
            Return MyBase.Channel.AccountQueryAsync(request)
        End Function
        
        Public Function AccountQueryAsync(ByVal AppKey As String, ByVal PolicyNumber As String) As System.Threading.Tasks.Task(Of NyaradzoAPI.AccountQueryResponse)
            Dim inValue As NyaradzoAPI.AccountQueryRequest = New NyaradzoAPI.AccountQueryRequest()
            inValue.Body = New NyaradzoAPI.AccountQueryRequestBody()
            inValue.Body.AppKey = AppKey
            inValue.Body.PolicyNumber = PolicyNumber
            Return CType(Me,NyaradzoAPI.NyaradzoSoap).AccountQueryAsync(inValue)
        End Function
    End Class
End Namespace
