//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZESAAPI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZESAAPI.CustomerInfoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZESAAPI.VendorBalanceResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZESAAPI.PurchaseTokenResponse))]
    public partial class BaseResponse : object
    {
        
        private int ReplyCodeField;
        
        private string ReplyMessageField;
        
        private string ReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReplyCode
        {
            get
            {
                return this.ReplyCodeField;
            }
            set
            {
                this.ReplyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReplyMessage
        {
            get
            {
                return this.ReplyMessageField;
            }
            set
            {
                this.ReplyMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfoResponse", Namespace="http://tempuri.org/")]
    public partial class CustomerInfoResponse : ZESAAPI.BaseResponse
    {
        
        private ZESAAPI.CustomerInfo CustomerInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ZESAAPI.CustomerInfo CustomerInfo
        {
            get
            {
                return this.CustomerInfoField;
            }
            set
            {
                this.CustomerInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VendorBalanceResponse", Namespace="http://tempuri.org/")]
    public partial class VendorBalanceResponse : ZESAAPI.BaseResponse
    {
        
        private ZESAAPI.VendorBalance VendorBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ZESAAPI.VendorBalance VendorBalance
        {
            get
            {
                return this.VendorBalanceField;
            }
            set
            {
                this.VendorBalanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseTokenResponse", Namespace="http://tempuri.org/")]
    public partial class PurchaseTokenResponse : ZESAAPI.BaseResponse
    {
        
        private decimal InitialBalanceField;
        
        private decimal FinalBalanceField;
        
        private ZESAAPI.PurchaseToken PurchaseTokenField;
        
        private ZESAAPI.CustomerInfo CustomerInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal InitialBalance
        {
            get
            {
                return this.InitialBalanceField;
            }
            set
            {
                this.InitialBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public decimal FinalBalance
        {
            get
            {
                return this.FinalBalanceField;
            }
            set
            {
                this.FinalBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ZESAAPI.PurchaseToken PurchaseToken
        {
            get
            {
                return this.PurchaseTokenField;
            }
            set
            {
                this.PurchaseTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ZESAAPI.CustomerInfo CustomerInfo
        {
            get
            {
                return this.CustomerInfoField;
            }
            set
            {
                this.CustomerInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseToken", Namespace="http://tempuri.org/")]
    public partial class PurchaseToken : object
    {
        
        private string ReferenceField;
        
        private ZESAAPI.DateTimeOffset DateField;
        
        private double AmountField;
        
        private string MeterNumberField;
        
        private string RawResponseField;
        
        private string ResponseCodeField;
        
        private string NarrativeField;
        
        private string VendorReferenceField;
        
        private ZESAAPI.TokenItem[] TokensField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public ZESAAPI.DateTimeOffset Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MeterNumber
        {
            get
            {
                return this.MeterNumberField;
            }
            set
            {
                this.MeterNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RawResponse
        {
            get
            {
                return this.RawResponseField;
            }
            set
            {
                this.RawResponseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Narrative
        {
            get
            {
                return this.NarrativeField;
            }
            set
            {
                this.NarrativeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string VendorReference
        {
            get
            {
                return this.VendorReferenceField;
            }
            set
            {
                this.VendorReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ZESAAPI.TokenItem[] Tokens
        {
            get
            {
                return this.TokensField;
            }
            set
            {
                this.TokensField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInfo", Namespace="http://tempuri.org/")]
    public partial class CustomerInfo : object
    {
        
        private string ReferenceField;
        
        private string CustomerNameField;
        
        private string AddressField;
        
        private string MeterNumberField;
        
        private string CurrencyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MeterNumber
        {
            get
            {
                return this.MeterNumberField;
            }
            set
            {
                this.MeterNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VendorBalance", Namespace="http://tempuri.org/")]
    public partial class VendorBalance : object
    {
        
        private string ReferenceField;
        
        private string BalanceField;
        
        private string AccountNumberField;
        
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateTimeOffset", Namespace="http://tempuri.org/")]
    public partial class DateTimeOffset : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenItem", Namespace="http://tempuri.org/")]
    public partial class TokenItem : object
    {
        
        private string ZesaReferenceField;
        
        private string TokenField;
        
        private double UnitsField;
        
        private double NetAmountField;
        
        private double ArrearsField;
        
        private double LevyField;
        
        private double TaxAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ZesaReference
        {
            get
            {
                return this.ZesaReferenceField;
            }
            set
            {
                this.ZesaReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Units
        {
            get
            {
                return this.UnitsField;
            }
            set
            {
                this.UnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double NetAmount
        {
            get
            {
                return this.NetAmountField;
            }
            set
            {
                this.NetAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Arrears
        {
            get
            {
                return this.ArrearsField;
            }
            set
            {
                this.ArrearsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Levy
        {
            get
            {
                return this.LevyField;
            }
            set
            {
                this.LevyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double TaxAmount
        {
            get
            {
                return this.TaxAmountField;
            }
            set
            {
                this.TaxAmountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZESAAPI.ZESASoap")]
    public interface ZESASoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PurchaseZESAToken", ReplyAction="*")]
        System.Threading.Tasks.Task<ZESAAPI.PurchaseZESATokenResponse> PurchaseZESATokenAsync(ZESAAPI.PurchaseZESATokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PurchaseZESATokenByCurrency", ReplyAction="*")]
        System.Threading.Tasks.Task<ZESAAPI.PurchaseZESATokenByCurrencyResponse> PurchaseZESATokenByCurrencyAsync(ZESAAPI.PurchaseZESATokenByCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<ZESAAPI.GetCustomerInfoResponse> GetCustomerInfoAsync(ZESAAPI.GetCustomerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<ZESAAPI.GetBalanceResponse> GetBalanceAsync(ZESAAPI.GetBalanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PurchaseZESATokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PurchaseZESAToken", Namespace="http://tempuri.org/", Order=0)]
        public ZESAAPI.PurchaseZESATokenRequestBody Body;
        
        public PurchaseZESATokenRequest()
        {
        }
        
        public PurchaseZESATokenRequest(ZESAAPI.PurchaseZESATokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchaseZESATokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MeterNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Reference;
        
        public PurchaseZESATokenRequestBody()
        {
        }
        
        public PurchaseZESATokenRequestBody(string AppKey, string MeterNumber, decimal Amount, string Reference)
        {
            this.AppKey = AppKey;
            this.MeterNumber = MeterNumber;
            this.Amount = Amount;
            this.Reference = Reference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PurchaseZESATokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PurchaseZESATokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZESAAPI.PurchaseZESATokenResponseBody Body;
        
        public PurchaseZESATokenResponse()
        {
        }
        
        public PurchaseZESATokenResponse(ZESAAPI.PurchaseZESATokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchaseZESATokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZESAAPI.PurchaseTokenResponse PurchaseZESATokenResult;
        
        public PurchaseZESATokenResponseBody()
        {
        }
        
        public PurchaseZESATokenResponseBody(ZESAAPI.PurchaseTokenResponse PurchaseZESATokenResult)
        {
            this.PurchaseZESATokenResult = PurchaseZESATokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PurchaseZESATokenByCurrencyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PurchaseZESATokenByCurrency", Namespace="http://tempuri.org/", Order=0)]
        public ZESAAPI.PurchaseZESATokenByCurrencyRequestBody Body;
        
        public PurchaseZESATokenByCurrencyRequest()
        {
        }
        
        public PurchaseZESATokenByCurrencyRequest(ZESAAPI.PurchaseZESATokenByCurrencyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchaseZESATokenByCurrencyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MeterNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Reference;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Currency;
        
        public PurchaseZESATokenByCurrencyRequestBody()
        {
        }
        
        public PurchaseZESATokenByCurrencyRequestBody(string AppKey, string MeterNumber, decimal Amount, string Reference, string Currency)
        {
            this.AppKey = AppKey;
            this.MeterNumber = MeterNumber;
            this.Amount = Amount;
            this.Reference = Reference;
            this.Currency = Currency;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PurchaseZESATokenByCurrencyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PurchaseZESATokenByCurrencyResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZESAAPI.PurchaseZESATokenByCurrencyResponseBody Body;
        
        public PurchaseZESATokenByCurrencyResponse()
        {
        }
        
        public PurchaseZESATokenByCurrencyResponse(ZESAAPI.PurchaseZESATokenByCurrencyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PurchaseZESATokenByCurrencyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZESAAPI.PurchaseTokenResponse PurchaseZESATokenByCurrencyResult;
        
        public PurchaseZESATokenByCurrencyResponseBody()
        {
        }
        
        public PurchaseZESATokenByCurrencyResponseBody(ZESAAPI.PurchaseTokenResponse PurchaseZESATokenByCurrencyResult)
        {
            this.PurchaseZESATokenByCurrencyResult = PurchaseZESATokenByCurrencyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerInfo", Namespace="http://tempuri.org/", Order=0)]
        public ZESAAPI.GetCustomerInfoRequestBody Body;
        
        public GetCustomerInfoRequest()
        {
        }
        
        public GetCustomerInfoRequest(ZESAAPI.GetCustomerInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MeterNumber;
        
        public GetCustomerInfoRequestBody()
        {
        }
        
        public GetCustomerInfoRequestBody(string AppKey, string MeterNumber)
        {
            this.AppKey = AppKey;
            this.MeterNumber = MeterNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZESAAPI.GetCustomerInfoResponseBody Body;
        
        public GetCustomerInfoResponse()
        {
        }
        
        public GetCustomerInfoResponse(ZESAAPI.GetCustomerInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZESAAPI.CustomerInfoResponse GetCustomerInfoResult;
        
        public GetCustomerInfoResponseBody()
        {
        }
        
        public GetCustomerInfoResponseBody(ZESAAPI.CustomerInfoResponse GetCustomerInfoResult)
        {
            this.GetCustomerInfoResult = GetCustomerInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://tempuri.org/", Order=0)]
        public ZESAAPI.GetBalanceRequestBody Body;
        
        public GetBalanceRequest()
        {
        }
        
        public GetBalanceRequest(ZESAAPI.GetBalanceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppKey;
        
        public GetBalanceRequestBody()
        {
        }
        
        public GetBalanceRequestBody(string AppKey)
        {
            this.AppKey = AppKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZESAAPI.GetBalanceResponseBody Body;
        
        public GetBalanceResponse()
        {
        }
        
        public GetBalanceResponse(ZESAAPI.GetBalanceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalanceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZESAAPI.VendorBalanceResponse GetBalanceResult;
        
        public GetBalanceResponseBody()
        {
        }
        
        public GetBalanceResponseBody(ZESAAPI.VendorBalanceResponse GetBalanceResult)
        {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ZESASoapChannel : ZESAAPI.ZESASoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ZESASoapClient : System.ServiceModel.ClientBase<ZESAAPI.ZESASoap>, ZESAAPI.ZESASoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZESASoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ZESASoapClient.GetBindingForEndpoint(endpointConfiguration), ZESASoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZESASoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZESASoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZESASoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZESASoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZESASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZESAAPI.PurchaseZESATokenResponse> ZESAAPI.ZESASoap.PurchaseZESATokenAsync(ZESAAPI.PurchaseZESATokenRequest request)
        {
            return base.Channel.PurchaseZESATokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZESAAPI.PurchaseZESATokenResponse> PurchaseZESATokenAsync(string AppKey, string MeterNumber, decimal Amount, string Reference)
        {
            ZESAAPI.PurchaseZESATokenRequest inValue = new ZESAAPI.PurchaseZESATokenRequest();
            inValue.Body = new ZESAAPI.PurchaseZESATokenRequestBody();
            inValue.Body.AppKey = AppKey;
            inValue.Body.MeterNumber = MeterNumber;
            inValue.Body.Amount = Amount;
            inValue.Body.Reference = Reference;
            return ((ZESAAPI.ZESASoap)(this)).PurchaseZESATokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZESAAPI.PurchaseZESATokenByCurrencyResponse> ZESAAPI.ZESASoap.PurchaseZESATokenByCurrencyAsync(ZESAAPI.PurchaseZESATokenByCurrencyRequest request)
        {
            return base.Channel.PurchaseZESATokenByCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZESAAPI.PurchaseZESATokenByCurrencyResponse> PurchaseZESATokenByCurrencyAsync(string AppKey, string MeterNumber, decimal Amount, string Reference, string Currency)
        {
            ZESAAPI.PurchaseZESATokenByCurrencyRequest inValue = new ZESAAPI.PurchaseZESATokenByCurrencyRequest();
            inValue.Body = new ZESAAPI.PurchaseZESATokenByCurrencyRequestBody();
            inValue.Body.AppKey = AppKey;
            inValue.Body.MeterNumber = MeterNumber;
            inValue.Body.Amount = Amount;
            inValue.Body.Reference = Reference;
            inValue.Body.Currency = Currency;
            return ((ZESAAPI.ZESASoap)(this)).PurchaseZESATokenByCurrencyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZESAAPI.GetCustomerInfoResponse> ZESAAPI.ZESASoap.GetCustomerInfoAsync(ZESAAPI.GetCustomerInfoRequest request)
        {
            return base.Channel.GetCustomerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZESAAPI.GetCustomerInfoResponse> GetCustomerInfoAsync(string AppKey, string MeterNumber)
        {
            ZESAAPI.GetCustomerInfoRequest inValue = new ZESAAPI.GetCustomerInfoRequest();
            inValue.Body = new ZESAAPI.GetCustomerInfoRequestBody();
            inValue.Body.AppKey = AppKey;
            inValue.Body.MeterNumber = MeterNumber;
            return ((ZESAAPI.ZESASoap)(this)).GetCustomerInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ZESAAPI.GetBalanceResponse> ZESAAPI.ZESASoap.GetBalanceAsync(ZESAAPI.GetBalanceRequest request)
        {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ZESAAPI.GetBalanceResponse> GetBalanceAsync(string AppKey)
        {
            ZESAAPI.GetBalanceRequest inValue = new ZESAAPI.GetBalanceRequest();
            inValue.Body = new ZESAAPI.GetBalanceRequestBody();
            inValue.Body.AppKey = AppKey;
            return ((ZESAAPI.ZESASoap)(this)).GetBalanceAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZESASoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ZESASoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZESASoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.31.60:8017/Zesa.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ZESASoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.31.60:8017/Zesa.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ZESASoap,
            
            ZESASoap12,
        }
    }
}
