'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EconetEPayAPI
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="EconetEPayAPI.EconetSoap")>  _
    Public Interface EconetSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RechargeMobile", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RechargeMobile(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As EconetEPayAPI.CreditResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RechargeMobile", ReplyAction:="*")>  _
        Function RechargeMobileAsync(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As System.Threading.Tasks.Task(Of EconetEPayAPI.CreditResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DebitMobile", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DebitMobile(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As EconetEPayAPI.DebitResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DebitMobile", ReplyAction:="*")>  _
        Function DebitMobileAsync(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As System.Threading.Tasks.Task(Of EconetEPayAPI.DebitResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EndUserBalance", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function EndUserBalance(ByVal TargetMobile As String, ByVal Reference As String) As EconetEPayAPI.BalanceResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EndUserBalance", ReplyAction:="*")>  _
        Function EndUserBalanceAsync(ByVal TargetMobile As String, ByVal Reference As String) As System.Threading.Tasks.Task(Of EconetEPayAPI.BalanceResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RechargeReversal", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RechargeReversal(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As EconetEPayAPI.CreditReversalResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RechargeReversal", ReplyAction:="*")>  _
        Function RechargeReversalAsync(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As System.Threading.Tasks.Task(Of EconetEPayAPI.CreditReversalResult)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://econetvas.econet.co.zw/")>  _
    Partial Public Class CreditResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private creditReqField As CreditRequest
        
        Private responseCodeField As String
        
        Private narrativeField As String
        
        Private initialBalanceField As Double
        
        Private daysAddedField As Integer
        
        Private finalBalanceField As Double
        
        Private expiryDateField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property creditReq() As CreditRequest
            Get
                Return Me.creditReqField
            End Get
            Set
                Me.creditReqField = value
                Me.RaisePropertyChanged("creditReq")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property responseCode() As String
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
                Me.RaisePropertyChanged("responseCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property narrative() As String
            Get
                Return Me.narrativeField
            End Get
            Set
                Me.narrativeField = value
                Me.RaisePropertyChanged("narrative")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property initialBalance() As Double
            Get
                Return Me.initialBalanceField
            End Get
            Set
                Me.initialBalanceField = value
                Me.RaisePropertyChanged("initialBalance")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property daysAdded() As Integer
            Get
                Return Me.daysAddedField
            End Get
            Set
                Me.daysAddedField = value
                Me.RaisePropertyChanged("daysAdded")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property finalBalance() As Double
            Get
                Return Me.finalBalanceField
            End Get
            Set
                Me.finalBalanceField = value
                Me.RaisePropertyChanged("finalBalance")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date", Order:=6)>  _
        Public Property expiryDate() As Date
            Get
                Return Me.expiryDateField
            End Get
            Set
                Me.expiryDateField = value
                Me.RaisePropertyChanged("expiryDate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://econetvas.econet.co.zw/")>  _
    Partial Public Class CreditRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private referenceField As String
        
        Private amountField As Double
        
        Private targetMobileNumberField As String
        
        Private serviceIdField As String
        
        Private serviceProviderIdField As String
        
        Private sourceMobileNumberField As String
        
        Private numberOfDaysField As Integer
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property reference() As String
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
                Me.RaisePropertyChanged("reference")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property amount() As Double
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("amount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property targetMobileNumber() As String
            Get
                Return Me.targetMobileNumberField
            End Get
            Set
                Me.targetMobileNumberField = value
                Me.RaisePropertyChanged("targetMobileNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property serviceId() As String
            Get
                Return Me.serviceIdField
            End Get
            Set
                Me.serviceIdField = value
                Me.RaisePropertyChanged("serviceId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property serviceProviderId() As String
            Get
                Return Me.serviceProviderIdField
            End Get
            Set
                Me.serviceProviderIdField = value
                Me.RaisePropertyChanged("serviceProviderId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property sourceMobileNumber() As String
            Get
                Return Me.sourceMobileNumberField
            End Get
            Set
                Me.sourceMobileNumberField = value
                Me.RaisePropertyChanged("sourceMobileNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property numberOfDays() As Integer
            Get
                Return Me.numberOfDaysField
            End Get
            Set
                Me.numberOfDaysField = value
                Me.RaisePropertyChanged("numberOfDays")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
                Me.RaisePropertyChanged("username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://econetvas.econet.co.zw/")>  _
    Partial Public Class CreditReversalResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private responseCodeField As String
        
        Private narrativeField As String
        
        Private originalCreditRequestField As CreditRequest
        
        Private initialBalanceField As Double
        
        Private finalBalanceField As Double
        
        Private numberOfDaysField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property responseCode() As String
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
                Me.RaisePropertyChanged("responseCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property narrative() As String
            Get
                Return Me.narrativeField
            End Get
            Set
                Me.narrativeField = value
                Me.RaisePropertyChanged("narrative")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property originalCreditRequest() As CreditRequest
            Get
                Return Me.originalCreditRequestField
            End Get
            Set
                Me.originalCreditRequestField = value
                Me.RaisePropertyChanged("originalCreditRequest")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property initialBalance() As Double
            Get
                Return Me.initialBalanceField
            End Get
            Set
                Me.initialBalanceField = value
                Me.RaisePropertyChanged("initialBalance")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property finalBalance() As Double
            Get
                Return Me.finalBalanceField
            End Get
            Set
                Me.finalBalanceField = value
                Me.RaisePropertyChanged("finalBalance")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property numberOfDays() As Integer
            Get
                Return Me.numberOfDaysField
            End Get
            Set
                Me.numberOfDaysField = value
                Me.RaisePropertyChanged("numberOfDays")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://econetvas.econet.co.zw/")>  _
    Partial Public Class BalanceRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private referenceField As String
        
        Private mobileNumberField As String
        
        Private serviceIdField As String
        
        Private serviceProviderIdField As String
        
        Private dedicatedAccountField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property reference() As String
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
                Me.RaisePropertyChanged("reference")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property mobileNumber() As String
            Get
                Return Me.mobileNumberField
            End Get
            Set
                Me.mobileNumberField = value
                Me.RaisePropertyChanged("mobileNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property serviceId() As String
            Get
                Return Me.serviceIdField
            End Get
            Set
                Me.serviceIdField = value
                Me.RaisePropertyChanged("serviceId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property serviceProviderId() As String
            Get
                Return Me.serviceProviderIdField
            End Get
            Set
                Me.serviceProviderIdField = value
                Me.RaisePropertyChanged("serviceProviderId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property dedicatedAccount() As Integer
            Get
                Return Me.dedicatedAccountField
            End Get
            Set
                Me.dedicatedAccountField = value
                Me.RaisePropertyChanged("dedicatedAccount")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://econetvas.econet.co.zw/")>  _
    Partial Public Class BalanceResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private balanceRequestField As BalanceRequest
        
        Private currentBalanceField As Double
        
        Private classOfServiceField As String
        
        Private responseCodeField As String
        
        Private narrativeField As String
        
        Private maximumCreditField As Double
        
        Private expiryDateField As Date
        
        Private minimumTopupField As Double
        
        Private suscriberTypeField As String
        
        Private maximumTopupField As Double
        
        Private activationDateField As Date
        
        Private platformField As String
        
        Private dedicatedAccountNumberField As String
        
        Private dedicatedAccountBalanceField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property balanceRequest() As BalanceRequest
            Get
                Return Me.balanceRequestField
            End Get
            Set
                Me.balanceRequestField = value
                Me.RaisePropertyChanged("balanceRequest")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property currentBalance() As Double
            Get
                Return Me.currentBalanceField
            End Get
            Set
                Me.currentBalanceField = value
                Me.RaisePropertyChanged("currentBalance")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property classOfService() As String
            Get
                Return Me.classOfServiceField
            End Get
            Set
                Me.classOfServiceField = value
                Me.RaisePropertyChanged("classOfService")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property responseCode() As String
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
                Me.RaisePropertyChanged("responseCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property narrative() As String
            Get
                Return Me.narrativeField
            End Get
            Set
                Me.narrativeField = value
                Me.RaisePropertyChanged("narrative")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property maximumCredit() As Double
            Get
                Return Me.maximumCreditField
            End Get
            Set
                Me.maximumCreditField = value
                Me.RaisePropertyChanged("maximumCredit")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date", Order:=6)>  _
        Public Property expiryDate() As Date
            Get
                Return Me.expiryDateField
            End Get
            Set
                Me.expiryDateField = value
                Me.RaisePropertyChanged("expiryDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property minimumTopup() As Double
            Get
                Return Me.minimumTopupField
            End Get
            Set
                Me.minimumTopupField = value
                Me.RaisePropertyChanged("minimumTopup")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property suscriberType() As String
            Get
                Return Me.suscriberTypeField
            End Get
            Set
                Me.suscriberTypeField = value
                Me.RaisePropertyChanged("suscriberType")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property maximumTopup() As Double
            Get
                Return Me.maximumTopupField
            End Get
            Set
                Me.maximumTopupField = value
                Me.RaisePropertyChanged("maximumTopup")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date", Order:=10)>  _
        Public Property activationDate() As Date
            Get
                Return Me.activationDateField
            End Get
            Set
                Me.activationDateField = value
                Me.RaisePropertyChanged("activationDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property platform() As String
            Get
                Return Me.platformField
            End Get
            Set
                Me.platformField = value
                Me.RaisePropertyChanged("platform")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property dedicatedAccountNumber() As String
            Get
                Return Me.dedicatedAccountNumberField
            End Get
            Set
                Me.dedicatedAccountNumberField = value
                Me.RaisePropertyChanged("dedicatedAccountNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property dedicatedAccountBalance() As String
            Get
                Return Me.dedicatedAccountBalanceField
            End Get
            Set
                Me.dedicatedAccountBalanceField = value
                Me.RaisePropertyChanged("dedicatedAccountBalance")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://econetvas.econet.co.zw/")>  _
    Partial Public Class DebitRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private referenceField As String
        
        Private amountField As Double
        
        Private serviceIdField As String
        
        Private serviceProviderIdField As String
        
        Private sourceMobileNumberField As String
        
        Private targetMobileNumberField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property reference() As String
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
                Me.RaisePropertyChanged("reference")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property amount() As Double
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
                Me.RaisePropertyChanged("amount")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property serviceId() As String
            Get
                Return Me.serviceIdField
            End Get
            Set
                Me.serviceIdField = value
                Me.RaisePropertyChanged("serviceId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property serviceProviderId() As String
            Get
                Return Me.serviceProviderIdField
            End Get
            Set
                Me.serviceProviderIdField = value
                Me.RaisePropertyChanged("serviceProviderId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property sourceMobileNumber() As String
            Get
                Return Me.sourceMobileNumberField
            End Get
            Set
                Me.sourceMobileNumberField = value
                Me.RaisePropertyChanged("sourceMobileNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property targetMobileNumber() As String
            Get
                Return Me.targetMobileNumberField
            End Get
            Set
                Me.targetMobileNumberField = value
                Me.RaisePropertyChanged("targetMobileNumber")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://econetvas.econet.co.zw/")>  _
    Partial Public Class DebitResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private debitReqField As DebitRequest
        
        Private responseCodeField As String
        
        Private narrativeField As String
        
        Private initialBalanceField As Double
        
        Private finalBalanceField As Double
        
        Private expiryDateField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property debitReq() As DebitRequest
            Get
                Return Me.debitReqField
            End Get
            Set
                Me.debitReqField = value
                Me.RaisePropertyChanged("debitReq")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property responseCode() As String
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
                Me.RaisePropertyChanged("responseCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property narrative() As String
            Get
                Return Me.narrativeField
            End Get
            Set
                Me.narrativeField = value
                Me.RaisePropertyChanged("narrative")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property initialBalance() As Double
            Get
                Return Me.initialBalanceField
            End Get
            Set
                Me.initialBalanceField = value
                Me.RaisePropertyChanged("initialBalance")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property finalBalance() As Double
            Get
                Return Me.finalBalanceField
            End Get
            Set
                Me.finalBalanceField = value
                Me.RaisePropertyChanged("finalBalance")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="date", Order:=5)>  _
        Public Property expiryDate() As Date
            Get
                Return Me.expiryDateField
            End Get
            Set
                Me.expiryDateField = value
                Me.RaisePropertyChanged("expiryDate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface EconetSoapChannel
        Inherits EconetEPayAPI.EconetSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EconetSoapClient
        Inherits System.ServiceModel.ClientBase(Of EconetEPayAPI.EconetSoap)
        Implements EconetEPayAPI.EconetSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function RechargeMobile(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As EconetEPayAPI.CreditResponse Implements EconetEPayAPI.EconetSoap.RechargeMobile
            Return MyBase.Channel.RechargeMobile(TargetMobile, Amount, Reference)
        End Function
        
        Public Function RechargeMobileAsync(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As System.Threading.Tasks.Task(Of EconetEPayAPI.CreditResponse) Implements EconetEPayAPI.EconetSoap.RechargeMobileAsync
            Return MyBase.Channel.RechargeMobileAsync(TargetMobile, Amount, Reference)
        End Function
        
        Public Function DebitMobile(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As EconetEPayAPI.DebitResponse Implements EconetEPayAPI.EconetSoap.DebitMobile
            Return MyBase.Channel.DebitMobile(TargetMobile, Amount, Reference)
        End Function
        
        Public Function DebitMobileAsync(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As System.Threading.Tasks.Task(Of EconetEPayAPI.DebitResponse) Implements EconetEPayAPI.EconetSoap.DebitMobileAsync
            Return MyBase.Channel.DebitMobileAsync(TargetMobile, Amount, Reference)
        End Function
        
        Public Function EndUserBalance(ByVal TargetMobile As String, ByVal Reference As String) As EconetEPayAPI.BalanceResponse Implements EconetEPayAPI.EconetSoap.EndUserBalance
            Return MyBase.Channel.EndUserBalance(TargetMobile, Reference)
        End Function
        
        Public Function EndUserBalanceAsync(ByVal TargetMobile As String, ByVal Reference As String) As System.Threading.Tasks.Task(Of EconetEPayAPI.BalanceResponse) Implements EconetEPayAPI.EconetSoap.EndUserBalanceAsync
            Return MyBase.Channel.EndUserBalanceAsync(TargetMobile, Reference)
        End Function
        
        Public Function RechargeReversal(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As EconetEPayAPI.CreditReversalResult Implements EconetEPayAPI.EconetSoap.RechargeReversal
            Return MyBase.Channel.RechargeReversal(TargetMobile, Amount, Reference)
        End Function
        
        Public Function RechargeReversalAsync(ByVal TargetMobile As String, ByVal Amount As Decimal, ByVal Reference As String) As System.Threading.Tasks.Task(Of EconetEPayAPI.CreditReversalResult) Implements EconetEPayAPI.EconetSoap.RechargeReversalAsync
            Return MyBase.Channel.RechargeReversalAsync(TargetMobile, Amount, Reference)
        End Function
    End Class
End Namespace
