//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelecelJuice
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopupResponse", Namespace="http://tempuri.org/")]
    public partial class TopupResponse : object
    {
        
        private TelecelJuice.ExtensionDataObject ExtensionData1Field;
        
        private string agentCodeField;
        
        private string sourceField;
        
        private string vendortransidField;
        
        private string vendorcodeField;
        
        private string productcodeField;
        
        private string destinationField;
        
        private string typeField;
        
        private string agenttransidField;
        
        private string amountField;
        
        private string pramtField;
        
        private string poamtField;
        
        private string transidField;
        
        private string walletBalanceField;
        
        private string preWalletBalanceField;
        
        private string feeField;
        
        private string processingfeeField;
        
        private string rangeField;
        
        private string servicetaxField;
        
        private string ecessField;
        
        private string hcessField;
        
        private string entaxField;
        
        private string vatField;
        
        private string taxField;
        
        private string clienttypeField;
        
        private string resultcodeField;
        
        private string resultdescriptionField;
        
        private string requestctsField;
        
        private string responsectsField;
        
        private string responseValueField;
        
        private string commentsField;
        
        private string smsvalField;
        
        private string oprwalletField;
        
        private string preoprwalletField;
        
        private string customerIdField;
        
        private string customerAccountIdField;
        
        private string refillIdField;
        
        private string pgAuthIdField;
        
        private string pgtransnameField;
        
        private string servicenameField;
        
        private string posCodeField;
        
        private string servicetypeField;
        
        private string pgtransIdField;
        
        private string channelIdField;
        
        private string validityField;
        
        private string pre_balanceField;
        
        private string post_balanceField;
        
        private string circleidField;
        
        private string stateField;
        
        private string distributeridField;
        
        private string authIdField;
        
        private string userIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TelecelJuice.ExtensionDataObject ExtensionData1
        {
            get
            {
                return this.ExtensionData1Field;
            }
            set
            {
                this.ExtensionData1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string agentCode
        {
            get
            {
                return this.agentCodeField;
            }
            set
            {
                this.agentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string vendortransid
        {
            get
            {
                return this.vendortransidField;
            }
            set
            {
                this.vendortransidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string vendorcode
        {
            get
            {
                return this.vendorcodeField;
            }
            set
            {
                this.vendorcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string productcode
        {
            get
            {
                return this.productcodeField;
            }
            set
            {
                this.productcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string pramt
        {
            get
            {
                return this.pramtField;
            }
            set
            {
                this.pramtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string poamt
        {
            get
            {
                return this.poamtField;
            }
            set
            {
                this.poamtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string walletBalance
        {
            get
            {
                return this.walletBalanceField;
            }
            set
            {
                this.walletBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string preWalletBalance
        {
            get
            {
                return this.preWalletBalanceField;
            }
            set
            {
                this.preWalletBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string fee
        {
            get
            {
                return this.feeField;
            }
            set
            {
                this.feeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string processingfee
        {
            get
            {
                return this.processingfeeField;
            }
            set
            {
                this.processingfeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string range
        {
            get
            {
                return this.rangeField;
            }
            set
            {
                this.rangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string servicetax
        {
            get
            {
                return this.servicetaxField;
            }
            set
            {
                this.servicetaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string ecess
        {
            get
            {
                return this.ecessField;
            }
            set
            {
                this.ecessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string hcess
        {
            get
            {
                return this.hcessField;
            }
            set
            {
                this.hcessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string entax
        {
            get
            {
                return this.entaxField;
            }
            set
            {
                this.entaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string vat
        {
            get
            {
                return this.vatField;
            }
            set
            {
                this.vatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string clienttype
        {
            get
            {
                return this.clienttypeField;
            }
            set
            {
                this.clienttypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string resultcode
        {
            get
            {
                return this.resultcodeField;
            }
            set
            {
                this.resultcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string resultdescription
        {
            get
            {
                return this.resultdescriptionField;
            }
            set
            {
                this.resultdescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string requestcts
        {
            get
            {
                return this.requestctsField;
            }
            set
            {
                this.requestctsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string responsects
        {
            get
            {
                return this.responsectsField;
            }
            set
            {
                this.responsectsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string responseValue
        {
            get
            {
                return this.responseValueField;
            }
            set
            {
                this.responseValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string smsval
        {
            get
            {
                return this.smsvalField;
            }
            set
            {
                this.smsvalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string oprwallet
        {
            get
            {
                return this.oprwalletField;
            }
            set
            {
                this.oprwalletField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string preoprwallet
        {
            get
            {
                return this.preoprwalletField;
            }
            set
            {
                this.preoprwalletField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string customerAccountId
        {
            get
            {
                return this.customerAccountIdField;
            }
            set
            {
                this.customerAccountIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string refillId
        {
            get
            {
                return this.refillIdField;
            }
            set
            {
                this.refillIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string pgAuthId
        {
            get
            {
                return this.pgAuthIdField;
            }
            set
            {
                this.pgAuthIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string pgtransname
        {
            get
            {
                return this.pgtransnameField;
            }
            set
            {
                this.pgtransnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string servicename
        {
            get
            {
                return this.servicenameField;
            }
            set
            {
                this.servicenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string posCode
        {
            get
            {
                return this.posCodeField;
            }
            set
            {
                this.posCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string servicetype
        {
            get
            {
                return this.servicetypeField;
            }
            set
            {
                this.servicetypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string pgtransId
        {
            get
            {
                return this.pgtransIdField;
            }
            set
            {
                this.pgtransIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string channelId
        {
            get
            {
                return this.channelIdField;
            }
            set
            {
                this.channelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string pre_balance
        {
            get
            {
                return this.pre_balanceField;
            }
            set
            {
                this.pre_balanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string post_balance
        {
            get
            {
                return this.post_balanceField;
            }
            set
            {
                this.post_balanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string circleid
        {
            get
            {
                return this.circleidField;
            }
            set
            {
                this.circleidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=48)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=49)]
        public string distributerid
        {
            get
            {
                return this.distributeridField;
            }
            set
            {
                this.distributeridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=50)]
        public string authId
        {
            get
            {
                return this.authIdField;
            }
            set
            {
                this.authIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=51)]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/")]
    public partial class ExtensionDataObject : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalanceResponse", Namespace="http://tempuri.org/")]
    public partial class BalanceResponse : object
    {
        
        private TelecelJuice.ExtensionDataObject ExtensionData1Field;
        
        private string agentcodeField;
        
        private string agentnameField;
        
        private string sourceField;
        
        private string destinationField;
        
        private string agenttransidField;
        
        private string vendorcodeField;
        
        private string amountField;
        
        private string transidField;
        
        private string resultcodeField;
        
        private string resultdescriptionField;
        
        private string requestctsField;
        
        private string responsectsField;
        
        private string clienttypeField;
        
        private string responsevalueField;
        
        private string commentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public TelecelJuice.ExtensionDataObject ExtensionData1
        {
            get
            {
                return this.ExtensionData1Field;
            }
            set
            {
                this.ExtensionData1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string agentcode
        {
            get
            {
                return this.agentcodeField;
            }
            set
            {
                this.agentcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string agentname
        {
            get
            {
                return this.agentnameField;
            }
            set
            {
                this.agentnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string agenttransid
        {
            get
            {
                return this.agenttransidField;
            }
            set
            {
                this.agenttransidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string vendorcode
        {
            get
            {
                return this.vendorcodeField;
            }
            set
            {
                this.vendorcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string transid
        {
            get
            {
                return this.transidField;
            }
            set
            {
                this.transidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string resultcode
        {
            get
            {
                return this.resultcodeField;
            }
            set
            {
                this.resultcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string resultdescription
        {
            get
            {
                return this.resultdescriptionField;
            }
            set
            {
                this.resultdescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string requestcts
        {
            get
            {
                return this.requestctsField;
            }
            set
            {
                this.requestctsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string responsects
        {
            get
            {
                return this.responsectsField;
            }
            set
            {
                this.responsectsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string clienttype
        {
            get
            {
                return this.clienttypeField;
            }
            set
            {
                this.clienttypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string responsevalue
        {
            get
            {
                return this.responsevalueField;
            }
            set
            {
                this.responsevalueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TelecelJuice.TelecelSoap")]
    public interface TelecelSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JuiceRecharge", ReplyAction="*")]
        System.Threading.Tasks.Task<TelecelJuice.JuiceRechargeResponse> JuiceRechargeAsync(TelecelJuice.JuiceRechargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JuiceRechargeUSD", ReplyAction="*")]
        System.Threading.Tasks.Task<TelecelJuice.JuiceRechargeUSDResponse> JuiceRechargeUSDAsync(TelecelJuice.JuiceRechargeUSDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JuiceBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<TelecelJuice.JuiceBalanceResponse> JuiceBalanceAsync(TelecelJuice.JuiceBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JuiceBalanceUSD", ReplyAction="*")]
        System.Threading.Tasks.Task<TelecelJuice.JuiceBalanceUSDResponse> JuiceBalanceUSDAsync(TelecelJuice.JuiceBalanceUSDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JuiceRechargeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JuiceRecharge", Namespace="http://tempuri.org/", Order=0)]
        public TelecelJuice.JuiceRechargeRequestBody Body;
        
        public JuiceRechargeRequest()
        {
        }
        
        public JuiceRechargeRequest(TelecelJuice.JuiceRechargeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JuiceRechargeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgentCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MPin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TargetMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TransID;
        
        public JuiceRechargeRequestBody()
        {
        }
        
        public JuiceRechargeRequestBody(string AgentCode, string MPin, string TargetMobile, string Amount, string TransID)
        {
            this.AgentCode = AgentCode;
            this.MPin = MPin;
            this.TargetMobile = TargetMobile;
            this.Amount = Amount;
            this.TransID = TransID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JuiceRechargeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JuiceRechargeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TelecelJuice.JuiceRechargeResponseBody Body;
        
        public JuiceRechargeResponse()
        {
        }
        
        public JuiceRechargeResponse(TelecelJuice.JuiceRechargeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JuiceRechargeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TelecelJuice.TopupResponse JuiceRechargeResult;
        
        public JuiceRechargeResponseBody()
        {
        }
        
        public JuiceRechargeResponseBody(TelecelJuice.TopupResponse JuiceRechargeResult)
        {
            this.JuiceRechargeResult = JuiceRechargeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JuiceRechargeUSDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JuiceRechargeUSD", Namespace="http://tempuri.org/", Order=0)]
        public TelecelJuice.JuiceRechargeUSDRequestBody Body;
        
        public JuiceRechargeUSDRequest()
        {
        }
        
        public JuiceRechargeUSDRequest(TelecelJuice.JuiceRechargeUSDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JuiceRechargeUSDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgentCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MPin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TargetMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TransID;
        
        public JuiceRechargeUSDRequestBody()
        {
        }
        
        public JuiceRechargeUSDRequestBody(string AgentCode, string MPin, string TargetMobile, string Amount, string TransID)
        {
            this.AgentCode = AgentCode;
            this.MPin = MPin;
            this.TargetMobile = TargetMobile;
            this.Amount = Amount;
            this.TransID = TransID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JuiceRechargeUSDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JuiceRechargeUSDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TelecelJuice.JuiceRechargeUSDResponseBody Body;
        
        public JuiceRechargeUSDResponse()
        {
        }
        
        public JuiceRechargeUSDResponse(TelecelJuice.JuiceRechargeUSDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JuiceRechargeUSDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TelecelJuice.TopupResponse JuiceRechargeUSDResult;
        
        public JuiceRechargeUSDResponseBody()
        {
        }
        
        public JuiceRechargeUSDResponseBody(TelecelJuice.TopupResponse JuiceRechargeUSDResult)
        {
            this.JuiceRechargeUSDResult = JuiceRechargeUSDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JuiceBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JuiceBalance", Namespace="http://tempuri.org/", Order=0)]
        public TelecelJuice.JuiceBalanceRequestBody Body;
        
        public JuiceBalanceRequest()
        {
        }
        
        public JuiceBalanceRequest(TelecelJuice.JuiceBalanceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JuiceBalanceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgentCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MPin;
        
        public JuiceBalanceRequestBody()
        {
        }
        
        public JuiceBalanceRequestBody(string AgentCode, string MPin)
        {
            this.AgentCode = AgentCode;
            this.MPin = MPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JuiceBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JuiceBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public TelecelJuice.JuiceBalanceResponseBody Body;
        
        public JuiceBalanceResponse()
        {
        }
        
        public JuiceBalanceResponse(TelecelJuice.JuiceBalanceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JuiceBalanceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TelecelJuice.BalanceResponse JuiceBalanceResult;
        
        public JuiceBalanceResponseBody()
        {
        }
        
        public JuiceBalanceResponseBody(TelecelJuice.BalanceResponse JuiceBalanceResult)
        {
            this.JuiceBalanceResult = JuiceBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JuiceBalanceUSDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JuiceBalanceUSD", Namespace="http://tempuri.org/", Order=0)]
        public TelecelJuice.JuiceBalanceUSDRequestBody Body;
        
        public JuiceBalanceUSDRequest()
        {
        }
        
        public JuiceBalanceUSDRequest(TelecelJuice.JuiceBalanceUSDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JuiceBalanceUSDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgentCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MPin;
        
        public JuiceBalanceUSDRequestBody()
        {
        }
        
        public JuiceBalanceUSDRequestBody(string AgentCode, string MPin)
        {
            this.AgentCode = AgentCode;
            this.MPin = MPin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JuiceBalanceUSDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JuiceBalanceUSDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TelecelJuice.JuiceBalanceUSDResponseBody Body;
        
        public JuiceBalanceUSDResponse()
        {
        }
        
        public JuiceBalanceUSDResponse(TelecelJuice.JuiceBalanceUSDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JuiceBalanceUSDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TelecelJuice.BalanceResponse JuiceBalanceUSDResult;
        
        public JuiceBalanceUSDResponseBody()
        {
        }
        
        public JuiceBalanceUSDResponseBody(TelecelJuice.BalanceResponse JuiceBalanceUSDResult)
        {
            this.JuiceBalanceUSDResult = JuiceBalanceUSDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface TelecelSoapChannel : TelecelJuice.TelecelSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class TelecelSoapClient : System.ServiceModel.ClientBase<TelecelJuice.TelecelSoap>, TelecelJuice.TelecelSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TelecelSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TelecelSoapClient.GetBindingForEndpoint(endpointConfiguration), TelecelSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TelecelSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TelecelSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TelecelSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TelecelSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TelecelSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelecelJuice.JuiceRechargeResponse> TelecelJuice.TelecelSoap.JuiceRechargeAsync(TelecelJuice.JuiceRechargeRequest request)
        {
            return base.Channel.JuiceRechargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelecelJuice.JuiceRechargeResponse> JuiceRechargeAsync(string AgentCode, string MPin, string TargetMobile, string Amount, string TransID)
        {
            TelecelJuice.JuiceRechargeRequest inValue = new TelecelJuice.JuiceRechargeRequest();
            inValue.Body = new TelecelJuice.JuiceRechargeRequestBody();
            inValue.Body.AgentCode = AgentCode;
            inValue.Body.MPin = MPin;
            inValue.Body.TargetMobile = TargetMobile;
            inValue.Body.Amount = Amount;
            inValue.Body.TransID = TransID;
            return ((TelecelJuice.TelecelSoap)(this)).JuiceRechargeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelecelJuice.JuiceRechargeUSDResponse> TelecelJuice.TelecelSoap.JuiceRechargeUSDAsync(TelecelJuice.JuiceRechargeUSDRequest request)
        {
            return base.Channel.JuiceRechargeUSDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelecelJuice.JuiceRechargeUSDResponse> JuiceRechargeUSDAsync(string AgentCode, string MPin, string TargetMobile, string Amount, string TransID)
        {
            TelecelJuice.JuiceRechargeUSDRequest inValue = new TelecelJuice.JuiceRechargeUSDRequest();
            inValue.Body = new TelecelJuice.JuiceRechargeUSDRequestBody();
            inValue.Body.AgentCode = AgentCode;
            inValue.Body.MPin = MPin;
            inValue.Body.TargetMobile = TargetMobile;
            inValue.Body.Amount = Amount;
            inValue.Body.TransID = TransID;
            return ((TelecelJuice.TelecelSoap)(this)).JuiceRechargeUSDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelecelJuice.JuiceBalanceResponse> TelecelJuice.TelecelSoap.JuiceBalanceAsync(TelecelJuice.JuiceBalanceRequest request)
        {
            return base.Channel.JuiceBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelecelJuice.JuiceBalanceResponse> JuiceBalanceAsync(string AgentCode, string MPin)
        {
            TelecelJuice.JuiceBalanceRequest inValue = new TelecelJuice.JuiceBalanceRequest();
            inValue.Body = new TelecelJuice.JuiceBalanceRequestBody();
            inValue.Body.AgentCode = AgentCode;
            inValue.Body.MPin = MPin;
            return ((TelecelJuice.TelecelSoap)(this)).JuiceBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TelecelJuice.JuiceBalanceUSDResponse> TelecelJuice.TelecelSoap.JuiceBalanceUSDAsync(TelecelJuice.JuiceBalanceUSDRequest request)
        {
            return base.Channel.JuiceBalanceUSDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TelecelJuice.JuiceBalanceUSDResponse> JuiceBalanceUSDAsync(string AgentCode, string MPin)
        {
            TelecelJuice.JuiceBalanceUSDRequest inValue = new TelecelJuice.JuiceBalanceUSDRequest();
            inValue.Body = new TelecelJuice.JuiceBalanceUSDRequestBody();
            inValue.Body.AgentCode = AgentCode;
            inValue.Body.MPin = MPin;
            return ((TelecelJuice.TelecelSoap)(this)).JuiceBalanceUSDAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TelecelSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TelecelSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TelecelSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.31.60:8017/telecel.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TelecelSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.31.60:8017/telecel.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TelecelSoap,
            
            TelecelSoap12,
        }
    }
}
