//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EconetBundle
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadDataResponse", Namespace="http://hot.co.zw:8007/")]
    public partial class LoadDataResponse : object
    {
        
        private string DescriptionField;
        
        private string ProviderReferenceField;
        
        private string SerialField;
        
        private int StatusField;
        
        private int StatusCodeField;
        
        private string RawResponseDataField;
        
        private double InitialWalletBalanceField;
        
        private double FinalWalletBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProviderReference
        {
            get
            {
                return this.ProviderReferenceField;
            }
            set
            {
                this.ProviderReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RawResponseData
        {
            get
            {
                return this.RawResponseDataField;
            }
            set
            {
                this.RawResponseDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double InitialWalletBalance
        {
            get
            {
                return this.InitialWalletBalanceField;
            }
            set
            {
                this.InitialWalletBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double FinalWalletBalance
        {
            get
            {
                return this.FinalWalletBalanceField;
            }
            set
            {
                this.FinalWalletBalanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadAirtimeResponse", Namespace="http://hot.co.zw:8007/")]
    public partial class LoadAirtimeResponse : object
    {
        
        private string DescriptionField;
        
        private string ProviderReferenceField;
        
        private string SerialField;
        
        private int StatusField;
        
        private int StatusCodeField;
        
        private string RawResponseDataField;
        
        private double InitialWalletBalanceField;
        
        private double FinalWalletBalanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProviderReference
        {
            get
            {
                return this.ProviderReferenceField;
            }
            set
            {
                this.ProviderReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RawResponseData
        {
            get
            {
                return this.RawResponseDataField;
            }
            set
            {
                this.RawResponseDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double InitialWalletBalance
        {
            get
            {
                return this.InitialWalletBalanceField;
            }
            set
            {
                this.InitialWalletBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double FinalWalletBalance
        {
            get
            {
                return this.FinalWalletBalanceField;
            }
            set
            {
                this.FinalWalletBalanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountBalanceResponse", Namespace="http://hot.co.zw:8007/")]
    public partial class AccountBalanceResponse : object
    {
        
        private EconetBundle.AccountBalance[] AccountBalancesField;
        
        private string RawResponseDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EconetBundle.AccountBalance[] AccountBalances
        {
            get
            {
                return this.AccountBalancesField;
            }
            set
            {
                this.AccountBalancesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RawResponseData
        {
            get
            {
                return this.RawResponseDataField;
            }
            set
            {
                this.RawResponseDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountBalance", Namespace="http://hot.co.zw:8007/")]
    public partial class AccountBalance : object
    {
        
        private long AmountField;
        
        private int CurrencyField;
        
        private int AccountTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int AccountType
        {
            get
            {
                return this.AccountTypeField;
            }
            set
            {
                this.AccountTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BundleProduct", Namespace="http://hot.co.zw:8007/")]
    public partial class BundleProduct : EconetBundle.Bundle
    {
        
        private int BundleIdField;
        
        private int BrandIdField;
        
        private string NetworkField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BundleId
        {
            get
            {
                return this.BundleIdField;
            }
            set
            {
                this.BundleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int BrandId
        {
            get
            {
                return this.BrandIdField;
            }
            set
            {
                this.BrandIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Network
        {
            get
            {
                return this.NetworkField;
            }
            set
            {
                this.NetworkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bundle", Namespace="http://hot.co.zw:8007/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EconetBundle.BundleProduct))]
    public partial class Bundle : object
    {
        
        private string ProductCodeField;
        
        private int AmountField;
        
        private string NameField;
        
        private string DescriptionField;
        
        private int ValidityPeriodField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ValidityPeriod
        {
            get
            {
                return this.ValidityPeriodField;
            }
            set
            {
                this.ValidityPeriodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmartbizAPIResponse", Namespace="http://hot.co.zw:8007/")]
    public partial class SmartbizAPIResponse : object
    {
        
        private bool SuccessField;
        
        private string MessageField;
        
        private int StatusCodeField;
        
        private string IsSmartBizNumberField;
        
        private bool SmartBizField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IsSmartBizNumber
        {
            get
            {
                return this.IsSmartBizNumberField;
            }
            set
            {
                this.IsSmartBizNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool SmartBiz
        {
            get
            {
                return this.SmartBizField;
            }
            set
            {
                this.SmartBizField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hot.co.zw:8007/", ConfigurationName="EconetBundle.EconetBundleSoap")]
    public interface EconetBundleSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hot.co.zw:8007/Recharge", ReplyAction="*")]
        System.Threading.Tasks.Task<EconetBundle.RechargeResponse> RechargeAsync(EconetBundle.RechargeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hot.co.zw:8007/RechargeAirtime", ReplyAction="*")]
        System.Threading.Tasks.Task<EconetBundle.RechargeAirtimeResponse> RechargeAirtimeAsync(EconetBundle.RechargeAirtimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hot.co.zw:8007/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<EconetBundle.GetBalanceResponse> GetBalanceAsync(EconetBundle.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hot.co.zw:8007/GetBundles", ReplyAction="*")]
        System.Threading.Tasks.Task<EconetBundle.GetBundlesResponse> GetBundlesAsync(EconetBundle.GetBundlesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hot.co.zw:8007/VerifySmartbizNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<EconetBundle.VerifySmartbizNumberResponse> VerifySmartbizNumberAsync(EconetBundle.VerifySmartbizNumberRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RechargeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Recharge", Namespace="http://hot.co.zw:8007/", Order=0)]
        public EconetBundle.RechargeRequestBody Body;
        
        public RechargeRequest()
        {
        }
        
        public RechargeRequest(EconetBundle.RechargeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hot.co.zw:8007/")]
    public partial class RechargeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TargetMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BundleCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long RechargeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Currency;
        
        public RechargeRequestBody()
        {
        }
        
        public RechargeRequestBody(string AppKey, string TargetMobile, string BundleCode, long RechargeId, string Currency)
        {
            this.AppKey = AppKey;
            this.TargetMobile = TargetMobile;
            this.BundleCode = BundleCode;
            this.RechargeId = RechargeId;
            this.Currency = Currency;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RechargeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RechargeResponse", Namespace="http://hot.co.zw:8007/", Order=0)]
        public EconetBundle.RechargeResponseBody Body;
        
        public RechargeResponse()
        {
        }
        
        public RechargeResponse(EconetBundle.RechargeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hot.co.zw:8007/")]
    public partial class RechargeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EconetBundle.LoadDataResponse RechargeResult;
        
        public RechargeResponseBody()
        {
        }
        
        public RechargeResponseBody(EconetBundle.LoadDataResponse RechargeResult)
        {
            this.RechargeResult = RechargeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RechargeAirtimeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RechargeAirtime", Namespace="http://hot.co.zw:8007/", Order=0)]
        public EconetBundle.RechargeAirtimeRequestBody Body;
        
        public RechargeAirtimeRequest()
        {
        }
        
        public RechargeAirtimeRequest(EconetBundle.RechargeAirtimeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hot.co.zw:8007/")]
    public partial class RechargeAirtimeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TargetMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long RechargeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Currency;
        
        public RechargeAirtimeRequestBody()
        {
        }
        
        public RechargeAirtimeRequestBody(string AppKey, string TargetMobile, decimal Amount, long RechargeId, string Currency)
        {
            this.AppKey = AppKey;
            this.TargetMobile = TargetMobile;
            this.Amount = Amount;
            this.RechargeId = RechargeId;
            this.Currency = Currency;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RechargeAirtimeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RechargeAirtimeResponse", Namespace="http://hot.co.zw:8007/", Order=0)]
        public EconetBundle.RechargeAirtimeResponseBody Body;
        
        public RechargeAirtimeResponse()
        {
        }
        
        public RechargeAirtimeResponse(EconetBundle.RechargeAirtimeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hot.co.zw:8007/")]
    public partial class RechargeAirtimeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EconetBundle.LoadAirtimeResponse RechargeAirtimeResult;
        
        public RechargeAirtimeResponseBody()
        {
        }
        
        public RechargeAirtimeResponseBody(EconetBundle.LoadAirtimeResponse RechargeAirtimeResult)
        {
            this.RechargeAirtimeResult = RechargeAirtimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://hot.co.zw:8007/", Order=0)]
        public EconetBundle.GetBalanceRequestBody Body;
        
        public GetBalanceRequest()
        {
        }
        
        public GetBalanceRequest(EconetBundle.GetBalanceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hot.co.zw:8007/")]
    public partial class GetBalanceRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Currency;
        
        public GetBalanceRequestBody()
        {
        }
        
        public GetBalanceRequestBody(string AppKey, string Currency)
        {
            this.AppKey = AppKey;
            this.Currency = Currency;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://hot.co.zw:8007/", Order=0)]
        public EconetBundle.GetBalanceResponseBody Body;
        
        public GetBalanceResponse()
        {
        }
        
        public GetBalanceResponse(EconetBundle.GetBalanceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hot.co.zw:8007/")]
    public partial class GetBalanceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EconetBundle.AccountBalanceResponse GetBalanceResult;
        
        public GetBalanceResponseBody()
        {
        }
        
        public GetBalanceResponseBody(EconetBundle.AccountBalanceResponse GetBalanceResult)
        {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBundlesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBundles", Namespace="http://hot.co.zw:8007/", Order=0)]
        public EconetBundle.GetBundlesRequestBody Body;
        
        public GetBundlesRequest()
        {
        }
        
        public GetBundlesRequest(EconetBundle.GetBundlesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hot.co.zw:8007/")]
    public partial class GetBundlesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppKey;
        
        public GetBundlesRequestBody()
        {
        }
        
        public GetBundlesRequestBody(string AppKey)
        {
            this.AppKey = AppKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBundlesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBundlesResponse", Namespace="http://hot.co.zw:8007/", Order=0)]
        public EconetBundle.GetBundlesResponseBody Body;
        
        public GetBundlesResponse()
        {
        }
        
        public GetBundlesResponse(EconetBundle.GetBundlesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hot.co.zw:8007/")]
    public partial class GetBundlesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EconetBundle.BundleProduct[] GetBundlesResult;
        
        public GetBundlesResponseBody()
        {
        }
        
        public GetBundlesResponseBody(EconetBundle.BundleProduct[] GetBundlesResult)
        {
            this.GetBundlesResult = GetBundlesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifySmartbizNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifySmartbizNumber", Namespace="http://hot.co.zw:8007/", Order=0)]
        public EconetBundle.VerifySmartbizNumberRequestBody Body;
        
        public VerifySmartbizNumberRequest()
        {
        }
        
        public VerifySmartbizNumberRequest(EconetBundle.VerifySmartbizNumberRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hot.co.zw:8007/")]
    public partial class VerifySmartbizNumberRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AppKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MobileNumber;
        
        public VerifySmartbizNumberRequestBody()
        {
        }
        
        public VerifySmartbizNumberRequestBody(string AppKey, string MobileNumber)
        {
            this.AppKey = AppKey;
            this.MobileNumber = MobileNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifySmartbizNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifySmartbizNumberResponse", Namespace="http://hot.co.zw:8007/", Order=0)]
        public EconetBundle.VerifySmartbizNumberResponseBody Body;
        
        public VerifySmartbizNumberResponse()
        {
        }
        
        public VerifySmartbizNumberResponse(EconetBundle.VerifySmartbizNumberResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://hot.co.zw:8007/")]
    public partial class VerifySmartbizNumberResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EconetBundle.SmartbizAPIResponse VerifySmartbizNumberResult;
        
        public VerifySmartbizNumberResponseBody()
        {
        }
        
        public VerifySmartbizNumberResponseBody(EconetBundle.SmartbizAPIResponse VerifySmartbizNumberResult)
        {
            this.VerifySmartbizNumberResult = VerifySmartbizNumberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface EconetBundleSoapChannel : EconetBundle.EconetBundleSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class EconetBundleSoapClient : System.ServiceModel.ClientBase<EconetBundle.EconetBundleSoap>, EconetBundle.EconetBundleSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EconetBundleSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(EconetBundleSoapClient.GetBindingForEndpoint(endpointConfiguration), EconetBundleSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EconetBundleSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EconetBundleSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EconetBundleSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EconetBundleSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EconetBundleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EconetBundle.RechargeResponse> EconetBundle.EconetBundleSoap.RechargeAsync(EconetBundle.RechargeRequest request)
        {
            return base.Channel.RechargeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EconetBundle.RechargeResponse> RechargeAsync(string AppKey, string TargetMobile, string BundleCode, long RechargeId, string Currency)
        {
            EconetBundle.RechargeRequest inValue = new EconetBundle.RechargeRequest();
            inValue.Body = new EconetBundle.RechargeRequestBody();
            inValue.Body.AppKey = AppKey;
            inValue.Body.TargetMobile = TargetMobile;
            inValue.Body.BundleCode = BundleCode;
            inValue.Body.RechargeId = RechargeId;
            inValue.Body.Currency = Currency;
            return ((EconetBundle.EconetBundleSoap)(this)).RechargeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EconetBundle.RechargeAirtimeResponse> EconetBundle.EconetBundleSoap.RechargeAirtimeAsync(EconetBundle.RechargeAirtimeRequest request)
        {
            return base.Channel.RechargeAirtimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EconetBundle.RechargeAirtimeResponse> RechargeAirtimeAsync(string AppKey, string TargetMobile, decimal Amount, long RechargeId, string Currency)
        {
            EconetBundle.RechargeAirtimeRequest inValue = new EconetBundle.RechargeAirtimeRequest();
            inValue.Body = new EconetBundle.RechargeAirtimeRequestBody();
            inValue.Body.AppKey = AppKey;
            inValue.Body.TargetMobile = TargetMobile;
            inValue.Body.Amount = Amount;
            inValue.Body.RechargeId = RechargeId;
            inValue.Body.Currency = Currency;
            return ((EconetBundle.EconetBundleSoap)(this)).RechargeAirtimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EconetBundle.GetBalanceResponse> EconetBundle.EconetBundleSoap.GetBalanceAsync(EconetBundle.GetBalanceRequest request)
        {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EconetBundle.GetBalanceResponse> GetBalanceAsync(string AppKey, string Currency)
        {
            EconetBundle.GetBalanceRequest inValue = new EconetBundle.GetBalanceRequest();
            inValue.Body = new EconetBundle.GetBalanceRequestBody();
            inValue.Body.AppKey = AppKey;
            inValue.Body.Currency = Currency;
            return ((EconetBundle.EconetBundleSoap)(this)).GetBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EconetBundle.GetBundlesResponse> EconetBundle.EconetBundleSoap.GetBundlesAsync(EconetBundle.GetBundlesRequest request)
        {
            return base.Channel.GetBundlesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EconetBundle.GetBundlesResponse> GetBundlesAsync(string AppKey)
        {
            EconetBundle.GetBundlesRequest inValue = new EconetBundle.GetBundlesRequest();
            inValue.Body = new EconetBundle.GetBundlesRequestBody();
            inValue.Body.AppKey = AppKey;
            return ((EconetBundle.EconetBundleSoap)(this)).GetBundlesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EconetBundle.VerifySmartbizNumberResponse> EconetBundle.EconetBundleSoap.VerifySmartbizNumberAsync(EconetBundle.VerifySmartbizNumberRequest request)
        {
            return base.Channel.VerifySmartbizNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<EconetBundle.VerifySmartbizNumberResponse> VerifySmartbizNumberAsync(string AppKey, string MobileNumber)
        {
            EconetBundle.VerifySmartbizNumberRequest inValue = new EconetBundle.VerifySmartbizNumberRequest();
            inValue.Body = new EconetBundle.VerifySmartbizNumberRequestBody();
            inValue.Body.AppKey = AppKey;
            inValue.Body.MobileNumber = MobileNumber;
            return ((EconetBundle.EconetBundleSoap)(this)).VerifySmartbizNumberAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EconetBundleSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.EconetBundleSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EconetBundleSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.31.60:8017/econetbundle.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.EconetBundleSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.31.60:8017/econetbundle.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            EconetBundleSoap,
            
            EconetBundleSoap12,
        }
    }
}
